/**
 * AOT artifact generation:
 * - routes.d.ts
 * - openapi.json
 * - client.d.ts
 * - manifest.json
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateOpenAPI } from "@ignus/shared";
import { DiagnosticCodes, errorMessage } from "../diagnostics";
import type { CompilerContext, CompilerOptions, RouteDef } from "../types";

export const writeGuarded = (
  file: string,
  content: string,
  ctx: CompilerContext,
  label: string,
): void => {
  try {
    writeFileSync(file, content);
    ctx.logger.info(`Generated ${label}`);
  } catch (error) {
    ctx.diagnostics.error({
      code: DiagnosticCodes.ArtifactWriteFailed,
      message: `Failed to write ${label}: ${errorMessage(error)}`,
      file,
    });
  }
};

const tsParamType = (paramNames: readonly string[]): string => {
  if (paramNames.length === 0) return "Record<string, never>";

  const lines = paramNames.map((name) => `    ${name}: string;`);
  return `{
${lines.join("\n")}
  }`;
};

export const generateRouteTypes = (routes: readonly RouteDef[]): string => {
  const lines: string[] = [];

  lines.push("// Auto-generated by Ignus AOT compiler.");
  lines.push("// Do not edit manually.");
  lines.push("");
  lines.push("export interface IgnusRoutes {");

  const byPath = new Map<string, RouteDef[]>();
  for (const route of routes) {
    const routePath = route.source.path;
    const group = byPath.get(routePath);
    if (group) group.push(route);
    else byPath.set(routePath, [route]);
  }

  for (const [path, defs] of byPath) {
    lines.push(`  ${JSON.stringify(path)}: {`);

    for (const route of defs) {
      const method = route.source.method.toLowerCase();
      lines.push(`    ${method}: {`);

      if (route.source.paramNames.length > 0) {
        lines.push(`      params: ${tsParamType(route.source.paramNames)};`);
      }

      if (route.analysis.usage.query) {
        lines.push("      query: Record<string, string | string[]>;");
      }

      if (route.analysis.usage.body) {
        lines.push("      body: unknown;");
      }

      lines.push("      response: unknown;");
      lines.push("    };");
    }

    lines.push("  };");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};

export const generateClientDts = (): string => {
  return `// Auto-generated by Ignus AOT compiler.
import type { IgnusRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnusRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnusClient = {
  [Path in keyof IgnusRoutes]: {
    [Method in keyof IgnusRoutes[Path]]: IgnusRouteHandler<IgnusRoutes[Path][Method]>;
  };
};

export declare function createApiClient(baseUrl?: string, init?: RequestInit): IgnusClient;
`;
};

/**
 * Generate a real typed client implementation (uses `createClient` from
 * `@ignus/core` behind a path/method proxy).
 */
export const generateClient = (routes: readonly RouteDef[]): string => {
  const routeEntries = routes
    .filter((r) => r.source.method !== "ALL")
    .map(
      (r) =>
        `  ${JSON.stringify(`${r.source.method.toLowerCase()} ${r.source.path}`)}: ${JSON.stringify(
          r.source.path,
        )},`,
    )
    .join("\n");

  // Each route's call shape is known at codegen time and emitted explicitly so
  // the runtime never has to guess from an opaque object — a plain-object
  // RequestInit used to be misread as `params` (dropping headers), and request
  // bodies were never sent at all.
  const routeArgsModes = routes
    .filter((r) => r.source.method !== "ALL")
    .map((r) => {
      const hasParams = r.source.paramNames.length > 0;
      const hasBody = r.analysis.usage.body === true;
      const mode = hasParams ? (hasBody ? "params+body" : "params") : hasBody ? "body" : "none";
      return `  ${JSON.stringify(r.source.path)}: ${JSON.stringify(mode)}`;
    })
    .join(",\n");

  return `// Auto-generated by Ignus AOT compiler.
import { createClient } from "@ignus/core";
import type { IgnusRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnusRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnusClient = {
  [Path in keyof IgnusRoutes]: {
    [Method in keyof IgnusRoutes[Path]]: IgnusRouteHandler<IgnusRoutes[Path][Method]>;
  };
};

const ROUTES: Record<string, string> = {
${routeEntries}
};

// Route path → call shape ("none" | "params" | "body" | "params+body").
const ROUTE_ARGS: Record<string, "none" | "params" | "body" | "params+body"> = {
${routeArgsModes}
};

const buildUrl = (path: string, params?: Record<string, string | number>): string => {
  let url = path;
  for (const [key, value] of Object.entries(params ?? {})) {
    url = url
      .replace(\`:\${key}\`, encodeURIComponent(String(value)))
      .replace(\`*\${key}\`, encodeURIComponent(String(value)));
  }
  return url;
};

// Deep-merge per-call init over the client-wide init so a per-call header
// doesn't clobber headers set on \`createApiClient\` (shallow spread would).
const mergeInit = (base: RequestInit | undefined, per: RequestInit | undefined): RequestInit => {
  const out: RequestInit = { ...base, ...per };
  if (base?.headers && per?.headers) {
    out.headers = {
      ...(base.headers as Record<string, string>),
      ...(per.headers as Record<string, string>),
    };
  }
  return out;
};

export function createApiClient(baseUrl = "", init?: RequestInit): IgnusClient {
  const client = createClient({ baseUrl });

  const routeHandler = (pathKey: string) => {
    const path = ROUTES[pathKey] ?? pathKey;
    const mode = ROUTE_ARGS[path] ?? "none";
    return new Proxy({} as Record<string, (...args: unknown[]) => Promise<unknown>>, {
      get(_, methodKey: string) {
        return async (...args: unknown[]) => {
          if (mode === "params+body") {
            const [params, body, requestInit] = args as [Record<string, string | number>, unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), body, mergeInit(init, requestInit));
          }
          if (mode === "params") {
            const [params, requestInit] = args as [Record<string, string | number>, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), undefined, mergeInit(init, requestInit));
          }
          if (mode === "body") {
            const [body, requestInit] = args as [unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), path, body, mergeInit(init, requestInit));
          }
          const [requestInit] = args as [RequestInit?];
          return client.request(methodKey.toUpperCase(), path, undefined, mergeInit(init, requestInit));
        };
      },
    });
  };

  return new Proxy({} as IgnusClient, {
    get(_, pathKey: string) {
      return routeHandler(pathKey);
    },
  });
}
`;
};

const toRouteDefinition = (route: RouteDef): Parameters<typeof generateOpenAPI>[1][number] => {
  const schemaDoc = route.decisions.schemaDoc as Record<string, unknown> | undefined;
  const detail = route.analysis.config?.detail;
  const definition: Parameters<typeof generateOpenAPI>[1][number] = {
    method: route.source.method,
    path: route.source.path,
    paramNames: route.source.paramNames,
    usesBody: route.analysis.usage.body === true,
  };
  if (schemaDoc) {
    definition.schema = {
      params: schemaDoc.params,
      query: schemaDoc.query,
      headers: schemaDoc.headers,
      body: schemaDoc.body,
      cookie: schemaDoc.cookie,
      response: schemaDoc.response,
    };
  }
  if (detail && typeof detail === "object") {
    definition.detail = detail as Record<string, unknown>;
  }
  return definition;
};

/**
 * OpenAPI 3.1 shaping for the built app. This delegates to the shared
 * `generateOpenAPI` (from `@ignus/shared`) — the single source of truth — so
 * the runtime docs and the compiled `openapi.json` can never drift. Only the
 * RouteDef → `RouteDefinition` mapping lives here.
 */
export const generateOpenApi = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
): Record<string, unknown> =>
  generateOpenAPI(
    {
      title: opts.serviceName ?? "ignus",
      version: "1.0.0",
    },
    routes.map(toRouteDefinition),
  ) as Record<string, unknown>;

export const generateManifest = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
): Record<string, unknown> => ({
  generatedAt: new Date().toISOString(),
  serviceName: opts.serviceName ?? "ignus",
  target: opts.target,
  optimizationLevel: opts.optimizationLevel,
  routes: routes.map((r) => ({
    method: r.source.method,
    path: r.source.path,
    file: r.source.file,
    isStatic: r.source.isStatic,
    isDynamic: r.source.isDynamic,
    segmentCount: r.source.segmentCount,
    isConstantResponse: r.analysis.isConstantResponse,
    responseType: r.analysis.responseType,
    hotnessScore: r.analysis.hotnessScore,
    paramNames: r.source.paramNames,
    hooks: r.analysis.hooks,
    usage: r.analysis.usage,
  })),
});

export const writeArtifacts = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
  ctx: CompilerContext,
): void => {
  mkdirSync(opts.outDir, { recursive: true });

  if (opts.generateTypes) {
    const types = generateRouteTypes(routes);
    writeGuarded(join(opts.outDir, "routes.d.ts"), types, ctx, "routes.d.ts");
  }

  if (opts.generateClient) {
    writeGuarded(join(opts.outDir, "client.d.ts"), generateClientDts(), ctx, "client.d.ts");
    writeGuarded(join(opts.outDir, "client.ts"), generateClient(routes), ctx, "client.ts");
  }

  if (opts.generateOpenAPI) {
    const openapi = generateOpenApi(routes, opts);
    writeGuarded(
      join(opts.outDir, "openapi.json"),
      JSON.stringify(openapi, null, 2),
      ctx,
      "openapi.json",
    );
  }

  const manifest = generateManifest(routes, opts);
  writeGuarded(
    join(opts.outDir, "manifest.json"),
    JSON.stringify(manifest, null, 2),
    ctx,
    "manifest.json",
  );
};
