/**
 * AOT artifact generation:
 * - routes.d.ts
 * - openapi.json
 * - client.d.ts
 * - manifest.json
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DiagnosticCodes, errorMessage } from "../diagnostics";
import type { CompilerContext, CompilerOptions, RouteDef } from "../types";

export const writeGuarded = (
  file: string,
  content: string,
  ctx: CompilerContext,
  label: string,
): void => {
  try {
    writeFileSync(file, content);
    ctx.logger.info(`Generated ${label}`);
  } catch (error) {
    ctx.diagnostics.error({
      code: DiagnosticCodes.ArtifactWriteFailed,
      message: `Failed to write ${label}: ${errorMessage(error)}`,
      file,
    });
  }
};

const tsParamType = (paramNames: readonly string[]): string => {
  if (paramNames.length === 0) return "Record<string, never>";

  const lines = paramNames.map((name) => `    ${name}: string;`);
  return `{
${lines.join("\n")}
  }`;
};

export const generateRouteTypes = (routes: readonly RouteDef[]): string => {
  const lines: string[] = [];

  lines.push("// Auto-generated by Flux AOT compiler.");
  lines.push("// Do not edit manually.");
  lines.push("");
  lines.push("export interface FluxRoutes {");

  const byPath = new Map<string, RouteDef[]>();
  for (const route of routes) {
    const routePath = route.source.path;
    const group = byPath.get(routePath);
    if (group) group.push(route);
    else byPath.set(routePath, [route]);
  }

  for (const [path, defs] of byPath) {
    lines.push(`  ${JSON.stringify(path)}: {`);

    for (const route of defs) {
      const method = route.source.method.toLowerCase();
      lines.push(`    ${method}: {`);

      if (route.source.paramNames.length > 0) {
        lines.push(`      params: ${tsParamType(route.source.paramNames)};`);
      }

      if (route.analysis.usage.query) {
        lines.push("      query: Record<string, string | string[]>;");
      }

      if (route.analysis.usage.body) {
        lines.push("      body: unknown;");
      }

      lines.push("      response: unknown;");
      lines.push("    };");
    }

    lines.push("  };");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};

export const generateClientDts = (): string => {
  return `// Auto-generated by Flux AOT compiler.
import type { FluxRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type FluxRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type FluxClient = {
  [Path in keyof FluxRoutes]: {
    [Method in keyof FluxRoutes[Path]]: FluxRouteHandler<FluxRoutes[Path][Method]>;
  };
};

export declare function createApiClient(baseUrl?: string, init?: RequestInit): FluxClient;
`;
};

/**
 * Generate a real typed client implementation (uses `createClient` from
 * `@flux/core` behind a path/method proxy).
 */
export const generateClient = (routes: readonly RouteDef[]): string => {
  const routeEntries = routes
    .filter((r) => r.source.method !== "ALL")
    .map(
      (r) =>
        `  ${JSON.stringify(`${r.source.method.toLowerCase()} ${r.source.path}`)}: ${JSON.stringify(
          r.source.path,
        )},`,
    )
    .join("\n");

  // Each route's call shape is known at codegen time and emitted explicitly so
  // the runtime never has to guess from an opaque object — a plain-object
  // RequestInit used to be misread as `params` (dropping headers), and request
  // bodies were never sent at all.
  const routeArgsModes = routes
    .filter((r) => r.source.method !== "ALL")
    .map((r) => {
      const hasParams = r.source.paramNames.length > 0;
      const hasBody = r.analysis.usage.body === true;
      const mode = hasParams ? (hasBody ? "params+body" : "params") : hasBody ? "body" : "none";
      return `  ${JSON.stringify(r.source.path)}: ${JSON.stringify(mode)}`;
    })
    .join(",\n");

  return `// Auto-generated by Flux AOT compiler.
import { createClient } from "@flux/core";
import type { FluxRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type FluxRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type FluxClient = {
  [Path in keyof FluxRoutes]: {
    [Method in keyof FluxRoutes[Path]]: FluxRouteHandler<FluxRoutes[Path][Method]>;
  };
};

const ROUTES: Record<string, string> = {
${routeEntries}
};

// Route path → call shape ("none" | "params" | "body" | "params+body").
const ROUTE_ARGS: Record<string, "none" | "params" | "body" | "params+body"> = {
${routeArgsModes}
};

const buildUrl = (path: string, params?: Record<string, string | number>): string => {
  let url = path;
  for (const [key, value] of Object.entries(params ?? {})) {
    url = url
      .replace(\`:\${key}\`, encodeURIComponent(String(value)))
      .replace(\`*\${key}\`, encodeURIComponent(String(value)));
  }
  return url;
};

// Deep-merge per-call init over the client-wide init so a per-call header
// doesn't clobber headers set on \`createApiClient\` (shallow spread would).
const mergeInit = (base: RequestInit | undefined, per: RequestInit | undefined): RequestInit => {
  const out: RequestInit = { ...base, ...per };
  if (base?.headers && per?.headers) {
    out.headers = {
      ...(base.headers as Record<string, string>),
      ...(per.headers as Record<string, string>),
    };
  }
  return out;
};

export function createApiClient(baseUrl = "", init?: RequestInit): FluxClient {
  const client = createClient({ baseUrl });

  const routeHandler = (pathKey: string) => {
    const path = ROUTES[pathKey] ?? pathKey;
    const mode = ROUTE_ARGS[path] ?? "none";
    return new Proxy({} as Record<string, (...args: unknown[]) => Promise<unknown>>, {
      get(_, methodKey: string) {
        return async (...args: unknown[]) => {
          if (mode === "params+body") {
            const [params, body, requestInit] = args as [Record<string, string | number>, unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), body, mergeInit(init, requestInit));
          }
          if (mode === "params") {
            const [params, requestInit] = args as [Record<string, string | number>, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), undefined, mergeInit(init, requestInit));
          }
          if (mode === "body") {
            const [body, requestInit] = args as [unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), path, body, mergeInit(init, requestInit));
          }
          const [requestInit] = args as [RequestInit?];
          return client.request(methodKey.toUpperCase(), path, undefined, mergeInit(init, requestInit));
        };
      },
    });
  };

  return new Proxy({} as FluxClient, {
    get(_, pathKey: string) {
      return routeHandler(pathKey);
    },
  });
}
`;
};

const toOpenApiPath = (path: string): string =>
  path.replace(/:([A-Za-z0-9_]+)/g, "{$1}").replace(/\*([A-Za-z0-9_]+)/g, "{$1}");

const stripId = (schema: unknown): unknown => {
  if (schema && typeof schema === "object") {
    const clone = { ...(schema as Record<string, unknown>) };
    delete clone.$id;
    return clone;
  }
  return schema;
};

const isStatusMap = (value: unknown): value is Record<string, unknown> => {
  if (!value || typeof value !== "object") return false;
  const keys = Object.keys(value);
  return keys.length > 0 && keys.every((k) => /^\d{3}$/.test(k));
};

const schemaToParameters = (
  schemaObj: unknown,
  location: "path" | "query" | "header",
  requiredOverride?: readonly string[],
): unknown[] => {
  if (!schemaObj || typeof schemaObj !== "object") return [];
  const schema = schemaObj as { properties?: Record<string, unknown>; required?: string[] };
  if (!schema.properties || typeof schema.properties !== "object") return [];

  const required = new Set(schema.required ?? requiredOverride ?? []);

  return Object.entries(schema.properties).map(([name, propSchema]) => ({
    name,
    in: location,
    required: location === "path" || required.has(name),
    schema: stripId(propSchema),
  }));
};

const statusDescription = (status: string): string => {
  const map: Record<string, string> = {
    "200": "OK",
    "201": "Created",
    "204": "No Content",
    "400": "Bad Request",
    "401": "Unauthorized",
    "403": "Forbidden",
    "404": "Not Found",
    "409": "Conflict",
    "422": "Unprocessable Entity",
    "429": "Too Many Requests",
    "500": "Internal Server Error",
  };
  return map[status] ?? "Response";
};

export const generateOpenApi = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
): Record<string, unknown> => {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const route of routes) {
    if (route.source.method === "ALL") continue;

    const openApiPath = toOpenApiPath(route.source.path);
    paths[openApiPath] ??= {};

    const operation: Record<string, unknown> = {
      operationId: `${route.source.method.toLowerCase()}_${openApiPath.replace(/[{}/]/g, "_")}`,
      responses: {
        "200": {
          description: "Successful response",
        },
      },
    };

    const detail = (route.analysis.config as any)?.detail;
    if (detail && typeof detail === "object") {
      Object.assign(operation, detail);
    }

    const schemaDoc = route.decisions.schemaDoc as Record<string, unknown> | undefined;
    const parameters: unknown[] = [];

    if (route.source.paramNames.length > 0) {
      if (schemaDoc?.params && typeof schemaDoc.params === "object") {
        parameters.push(...schemaToParameters(schemaDoc.params, "path", route.source.paramNames));
      } else {
        for (const name of route.source.paramNames) {
          parameters.push({ name, in: "path", required: true, schema: { type: "string" } });
        }
      }
    }

    if (schemaDoc?.query && typeof schemaDoc.query === "object") {
      parameters.push(...schemaToParameters(schemaDoc.query, "query"));
    }

    if (schemaDoc?.headers && typeof schemaDoc.headers === "object") {
      parameters.push(...schemaToParameters(schemaDoc.headers, "header"));
    }

    if (parameters.length > 0) {
      operation.parameters = parameters;
    }

    if (schemaDoc?.body) {
      operation.requestBody = {
        content: {
          "application/json": {
            schema: stripId(schemaDoc.body),
          },
        },
      };
    } else if (route.analysis.usage.body) {
      operation.requestBody = {
        content: {
          "application/json": {
            schema: { type: "object" },
          },
        },
      };
    }

    const responseSchema = schemaDoc?.response;
    if (responseSchema) {
      const responses: Record<string, unknown> = {};

      if (isStatusMap(responseSchema)) {
        for (const [status, schema] of Object.entries(responseSchema)) {
          responses[status] = {
            description: statusDescription(status),
            content: { "application/json": { schema: stripId(schema) } },
          };
        }
      } else {
        responses["200"] = {
          description: "Successful response",
          content: { "application/json": { schema: stripId(responseSchema) } },
        };
      }

      operation.responses = responses;
    }

    paths[openApiPath][route.source.method.toLowerCase()] = operation;
  }

  return {
    openapi: "3.1.0",
    info: {
      title: opts.serviceName ?? "flux",
      version: "1.0.0",
    },
    paths,
  };
};

export const generateManifest = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
): Record<string, unknown> => ({
  generatedAt: new Date().toISOString(),
  serviceName: opts.serviceName ?? "flux",
  target: opts.target,
  optimizationLevel: opts.optimizationLevel,
  routes: routes.map((r) => ({
    method: r.source.method,
    path: r.source.path,
    file: r.source.file,
    isStatic: r.source.isStatic,
    isDynamic: r.source.isDynamic,
    segmentCount: r.source.segmentCount,
    isConstantResponse: r.analysis.isConstantResponse,
    responseType: r.analysis.responseType,
    hotnessScore: r.analysis.hotnessScore,
    paramNames: r.source.paramNames,
    hooks: r.analysis.hooks,
    usage: r.analysis.usage,
  })),
});

export const writeArtifacts = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
  ctx: CompilerContext,
): void => {
  mkdirSync(opts.outDir, { recursive: true });

  if (opts.generateTypes) {
    const types = generateRouteTypes(routes);
    writeGuarded(join(opts.outDir, "routes.d.ts"), types, ctx, "routes.d.ts");
  }

  if (opts.generateClient) {
    writeGuarded(join(opts.outDir, "client.d.ts"), generateClientDts(), ctx, "client.d.ts");
    writeGuarded(join(opts.outDir, "client.ts"), generateClient(routes), ctx, "client.ts");
  }

  if (opts.generateOpenAPI) {
    const openapi = generateOpenApi(routes, opts);
    writeGuarded(
      join(opts.outDir, "openapi.json"),
      JSON.stringify(openapi, null, 2),
      ctx,
      "openapi.json",
    );
  }

  const manifest = generateManifest(routes, opts);
  writeGuarded(
    join(opts.outDir, "manifest.json"),
    JSON.stringify(manifest, null, 2),
    ctx,
    "manifest.json",
  );
};
