/**
 * AOT artifact generation:
 * - routes.d.ts
 * - openapi.json
 * - client.d.ts
 * - manifest.json
 */

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import type { RouteDef, CompilerOptions } from "../types";
import type { Logger } from "../logger";

const tsParamType = (paramNames: readonly string[]): string => {
  if (paramNames.length === 0) return "Record<string, never>";

  const lines = paramNames.map((name) => `    ${name}: string;`);
  return `{
${lines.join("\n")}
  }`;
};

export const generateRouteTypes = (routes: readonly RouteDef[]): string => {
  const lines: string[] = [];

  lines.push("// Auto-generated by Flux AOT compiler.");
  lines.push("// Do not edit manually.");
  lines.push("");
  lines.push("export interface FluxRoutes {");

  const byPath = new Map<string, RouteDef[]>();
  for (const route of routes) {
    const group = byPath.get(route.path);
    if (group) group.push(route);
    else byPath.set(route.path, [route]);
  }

  for (const [path, defs] of byPath) {
    lines.push(`  ${JSON.stringify(path)}: {`);

    for (const route of defs) {
      const method = route.method.toLowerCase();
      lines.push(`    ${method}: {`);

      if (route.paramNames.length > 0) {
        lines.push(`      params: ${tsParamType(route.paramNames)};`);
      }

      if (route.usage.query) {
        lines.push("      query: Record<string, string | string[]>;");
      }

      if (route.usage.body) {
        lines.push("      body: unknown;");
      }

      lines.push("      response: unknown;");
      lines.push("    };");
    }

    lines.push("  };");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};

export const generateClientDts = (): string => {
  return `// Auto-generated by Flux AOT compiler.
import type { FluxRoutes } from "./routes";

export type FluxClient = {
  [Path in keyof FluxRoutes]: {
    [Method in keyof FluxRoutes[Path]]: (
      ...args: FluxRoutes[Path][Method] extends { params: infer P }
        ? [params: P, init?: RequestInit]
        : [init?: RequestInit]
    ) => Promise<Response>;
  };
};

export declare function createClient(baseUrl?: string): FluxClient;
`;
};

const toOpenApiPath = (path: string): string =>
  path.replace(/:([A-Za-z0-9_]+)/g, "{$1}").replace(/\*([A-Za-z0-9_]+)/g, "{$1}");

export const generateOpenApi = (
  routes: readonly RouteDef[],
  opts: CompilerOptions
): Record<string, unknown> => {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const route of routes) {
    if (route.method === "ALL") continue;

    const openApiPath = toOpenApiPath(route.path);
    paths[openApiPath] ??= {};

    const operation: Record<string, unknown> = {
      operationId: `${route.method.toLowerCase()}_${openApiPath.replace(/[{}\/]/g, "_")}`,
      responses: {
        "200": {
          description: "Successful response",
        },
      },
    };

    const detail = (route.config as any)?.detail;
    if (detail && typeof detail === "object") {
      Object.assign(operation, detail);
    }

    if (route.paramNames.length > 0) {
      operation.parameters = route.paramNames.map((name) => ({
        name,
        in: "path",
        required: true,
        schema: { type: "string" },
      }));
    }

    if (route.usage.body) {
      operation.requestBody = {
        content: {
          "application/json": {
            schema: { type: "object" },
          },
        },
      };
    }

    paths[openApiPath][route.method.toLowerCase()] = operation;
  }

  return {
    openapi: "3.1.0",
    info: {
      title: opts.serviceName ?? "flux",
      version: "1.0.0",
    },
    paths,
  };
};

export const generateManifest = (
  routes: readonly RouteDef[],
  opts: CompilerOptions
): Record<string, unknown> => ({
  generatedAt: new Date().toISOString(),
  serviceName: opts.serviceName ?? "flux",
  target: opts.target,
  routes: routes.map((r) => ({
    method: r.method,
    path: r.path,
    file: r.file,
    isStatic: r.isStatic,
    isDynamic: r.isDynamic,
    isConstantResponse: r.isConstantResponse,
    responseType: r.responseType,
    paramNames: r.paramNames,
    hooks: r.hooks,
    usage: r.usage,
  })),
});

export const writeArtifacts = (
  routes: readonly RouteDef[],
  opts: CompilerOptions,
  logger: Logger
): void => {
  mkdirSync(opts.outDir, { recursive: true });

  if (opts.generateTypes) {
    const types = generateRouteTypes(routes);
    writeFileSync(join(opts.outDir, "routes.d.ts"), types);
    logger.info("Generated routes.d.ts");
  }

  if (opts.generateClient) {
    writeFileSync(join(opts.outDir, "client.d.ts"), generateClientDts());
    logger.info("Generated client.d.ts");
  }

  if (opts.generateOpenAPI) {
    const openapi = generateOpenApi(routes, opts);
    writeFileSync(
      join(opts.outDir, "openapi.json"),
      JSON.stringify(openapi, null, 2)
    );
    logger.info("Generated openapi.json");
  }

  const manifest = generateManifest(routes, opts);
  writeFileSync(join(opts.outDir, "manifest.json"), JSON.stringify(manifest, null, 2));
  logger.info("Generated manifest.json");
};
