/**
 * @fileoverview Generated SDK client artifacts — `client.d.ts` + `client.ts`.
 */

import type { RouteIR } from "../../types";

export const generateClientDts = (): string => {
  return `// Auto-generated by Ignex AOT compiler.
import type { IgnexRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnexRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnexClient = {
  [Path in keyof IgnexRoutes]: {
    [Method in keyof IgnexRoutes[Path]]: IgnexRouteHandler<IgnexRoutes[Path][Method]>;
  };
};

export declare function createApiClient(baseUrl?: string, init?: RequestInit): IgnexClient;
`;
};

/**
 * Generate a real typed client implementation (uses `createClient` from
 * `@ignex/core` behind a path/method proxy).
 */
export const generateClient = (routes: readonly RouteIR[]): string => {
  const routeEntries = routes
    .filter((r) => r.source.method !== "ALL")
    .map(
      (r) =>
        `  ${JSON.stringify(`${r.source.method.toLowerCase()} ${r.source.path}`)}: ${JSON.stringify(
          r.source.path,
        )},`,
    )
    .join("\n");

  // Each route's call shape is known at codegen time and emitted explicitly so
  // the runtime never has to guess from an opaque object — a plain-object
  // RequestInit used to be misread as `params` (dropping headers), and request
  // bodies were never sent at all.
  const routeArgsModes = routes
    .filter((r) => r.source.method !== "ALL")
    .map((r) => {
      const hasParams = r.source.paramNames.length > 0;
      const hasBody = r.analysis.usage.body === true;
      const mode = hasParams ? (hasBody ? "params+body" : "params") : hasBody ? "body" : "none";
      return `  ${JSON.stringify(r.source.path)}: ${JSON.stringify(mode)}`;
    })
    .join(",\n");

  return `// Auto-generated by Ignex AOT compiler.
import { createClient } from "@ignex/core";
import type { IgnexRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnexRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnexClient = {
  [Path in keyof IgnexRoutes]: {
    [Method in keyof IgnexRoutes[Path]]: IgnexRouteHandler<IgnexRoutes[Path][Method]>;
  };
};

const ROUTES: Record<string, string> = {
${routeEntries}
};

// Route path → call shape ("none" | "params" | "body" | "params+body").
const ROUTE_ARGS: Record<string, "none" | "params" | "body" | "params+body"> = {
${routeArgsModes}
};

const buildUrl = (path: string, params?: Record<string, string | number>): string => {
  let url = path;
  for (const [key, value] of Object.entries(params ?? {})) {
    url = url
      .replace(\`:\${key}\`, encodeURIComponent(String(value)))
      .replace(\`*\${key}\`, encodeURIComponent(String(value)));
  }
  return url;
};

// Deep-merge per-call init over the client-wide init so a per-call header
// doesn't clobber headers set on \`createApiClient\` (shallow spread would).
const mergeInit = (base: RequestInit | undefined, per: RequestInit | undefined): RequestInit => {
  const out: RequestInit = { ...base, ...per };
  if (base?.headers && per?.headers) {
    out.headers = {
      ...(base.headers as Record<string, string>),
      ...(per.headers as Record<string, string>),
    };
  }
  return out;
};

export function createApiClient(baseUrl = "", init?: RequestInit): IgnexClient {
  const client = createClient({ baseUrl });

  const routeHandler = (pathKey: string) => {
    const path = ROUTES[pathKey] ?? pathKey;
    const mode = ROUTE_ARGS[path] ?? "none";
    return new Proxy({} as Record<string, (...args: unknown[]) => Promise<unknown>>, {
      get(_, methodKey: string) {
        return async (...args: unknown[]) => {
          if (mode === "params+body") {
            const [params, body, requestInit] = args as [Record<string, string | number>, unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), body, mergeInit(init, requestInit));
          }
          if (mode === "params") {
            const [params, requestInit] = args as [Record<string, string | number>, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), undefined, mergeInit(init, requestInit));
          }
          if (mode === "body") {
            const [body, requestInit] = args as [unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), path, body, mergeInit(init, requestInit));
          }
          const [requestInit] = args as [RequestInit?];
          return client.request(methodKey.toUpperCase(), path, undefined, mergeInit(init, requestInit));
        };
      },
    });
  };

  return new Proxy({} as IgnexClient, {
    get(_, pathKey: string) {
      return routeHandler(pathKey);
    },
  });
}
`;
};
