/**
 * @fileoverview `routes.d.ts` type artifact generation.
 */

import type { RouteIR } from "../../types";

const tsParamType = (paramNames: readonly string[]): string => {
  if (paramNames.length === 0) return "Record<string, never>";

  const lines = paramNames.map((name) => `    ${name}: string;`);
  return `{
${lines.join("\n")}
  }`;
};

/**
 * Generate `routes.d.ts` — the typed `IgnexRoutes` interface (per-route
 * params/body/response types) for the emitted server.
 */
export const generateRouteTypes = (routes: readonly RouteIR[]): string => {
  const lines: string[] = [];

  lines.push("// Auto-generated by Ignex AOT compiler.");
  lines.push("// Do not edit manually.");
  lines.push("");
  lines.push("export interface IgnexRoutes {");

  const byPath = new Map<string, RouteIR[]>();
  for (const route of routes) {
    const routePath = route.source.path;
    const group = byPath.get(routePath);
    if (group) group.push(route);
    else byPath.set(routePath, [route]);
  }

  for (const [path, defs] of byPath) {
    lines.push(`  ${JSON.stringify(path)}: {`);

    for (const route of defs) {
      const method = route.source.method.toLowerCase();
      lines.push(`    ${method}: {`);

      if (route.source.paramNames.length > 0) {
        lines.push(`      params: ${tsParamType(route.source.paramNames)};`);
      }

      if (route.analysis.usage.query) {
        lines.push("      query: Record<string, string | string[]>;");
      }

      if (route.analysis.usage.body) {
        lines.push("      body: unknown;");
      }

      lines.push("      response: unknown;");
      lines.push("    };");
    }

    lines.push("  };");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};
