/**
 * @fileoverview `routes.d.ts` type artifact generation.
 */

import type { CompilerOptions, ModuleInfo, RouteIR } from "../../types";
import { walk } from "../../utils/ast";
import { toImportPath } from "../codegen/config";

const tsParamType = (paramNames: readonly string[]): string => {
  if (paramNames.length === 0) return "Record<string, never>";

  const lines = paramNames.map((name) => `    ${name}: string;`);
  return `{
${lines.join("\n")}
  }`;
};

/** True when the module has a referenceable `export const schema = {...}`. */
const hasNamedSchemaConst = (ast: unknown): boolean => {
  if (!ast || typeof ast !== "object") return false;
  let found = false;
  walk(ast as never, (n) => {
    if (found) return false;
    if (n.type === "ExportNamedDeclaration" && n.declaration?.type === "VariableDeclaration") {
      for (const d of n.declaration.declarations ?? []) {
        if (d.id?.type === "Identifier" && d.id.name === "schema") {
          found = true;
          return false;
        }
      }
    }
    return undefined;
  });
  return found;
};

/**
 * Generate `routes.d.ts` — the typed `IgnexRoutes` interface (per-route
 * params/body/response types) for the emitted server.
 *
 * When a route module exports a named `schema` const (the TypeBox schema-first
 * pattern: `export const schema = { body: Type.Object({...}) }`) AND declares
 * a `body` schema, the emitted body type references `Static<typeof schema.body>`
 * so the generated client / typed-handler surface is REAL instead of `unknown`.
 * Routes without a referenceable TypeBox schema keep `unknown` — no risk of a
 * broken `routes.d.ts`. Requires `modules` + `opts` (the caller passes them
 * from the build pipeline); omitted (e.g. unit callers) → all `unknown`.
 */
export const generateRouteTypes = (
  routes: readonly RouteIR[],
  modules?: readonly ModuleInfo[],
  opts?: CompilerOptions,
): string => {
  const typeImports = new Map<string, string>(); // schema import name → abs module path
  const typedBodies = new Map<RouteIR, string>();

  if (modules !== undefined && opts !== undefined) {
    collectTypedBodies(routes, modules, typeImports, typedBodies);
  }

  const lines: string[] = [];

  lines.push("// Auto-generated by Ignex AOT compiler.");
  lines.push("// Do not edit manually.");
  lines.push("");
  emitTypeImports(lines, typeImports, opts);
  lines.push("export interface IgnexRoutes {");

  const byPath = groupByPath(routes);
  for (const [path, defs] of byPath) {
    lines.push(`  ${JSON.stringify(path)}: {`);
    for (const route of defs) {
      emitRouteMethod(lines, route, typedBodies);
    }
    lines.push("  };");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};

/** Collect `Static<typeof schema.body>` typed bodies for schema-const routes. */
const collectTypedBodies = (
  routes: readonly RouteIR[],
  modules: readonly ModuleInfo[],
  typeImports: Map<string, string>,
  typedBodies: Map<RouteIR, string>,
): void => {
  for (const route of routes) {
    const mod = modules[route.source.moduleIdx];
    if (!mod?.ast || !hasNamedSchemaConst(mod.ast)) continue;
    const schemaDoc = route.decisions.schemaDoc as { body?: unknown } | undefined;
    if (!schemaDoc?.body) continue;
    const importName = `schema_${route.codegen.handlerRef}`;
    typeImports.set(importName, mod.path);
    typedBodies.set(route, `Static<typeof ${importName}.body>`);
  }
};

/** Emit the type-only imports (typebox + per-route `schema` module references). */
const emitTypeImports = (
  lines: string[],
  typeImports: Map<string, string>,
  opts: CompilerOptions | undefined,
): void => {
  if (typeImports.size === 0 || opts === undefined) return;
  lines.push('import type { Static } from "typebox";');
  for (const [name, abs] of typeImports) {
    lines.push(
      `import type { schema as ${name} } from ${JSON.stringify(toImportPath(abs, opts))};`,
    );
  }
  lines.push("");
};

const groupByPath = (routes: readonly RouteIR[]): Map<string, RouteIR[]> => {
  const byPath = new Map<string, RouteIR[]>();
  for (const route of routes) {
    const routePath = route.source.path;
    const group = byPath.get(routePath);
    if (group) group.push(route);
    else byPath.set(routePath, [route]);
  }
  return byPath;
};

/** Emit one method block of the `IgnexRoutes` interface. */
const emitRouteMethod = (
  lines: string[],
  route: RouteIR,
  typedBodies: Map<RouteIR, string>,
): void => {
  const method = route.source.method.toLowerCase();
  lines.push(`    ${method}: {`);

  if (route.source.paramNames.length > 0) {
    lines.push(`      params: ${tsParamType(route.source.paramNames)};`);
  }

  if (route.analysis.usage.query) {
    lines.push("      query: Record<string, string | string[]>;");
  }

  // A body type is emitted when the handler reads `ctx.body` OR the route
  // declares a body schema (schema-first routes validate the body even if
  // the handler never reads it). Prefer the typed `Static<typeof …>` form.
  const schemaDoc = route.decisions?.schemaDoc as { body?: unknown } | undefined;
  if (route.analysis.usage.body || schemaDoc?.body !== undefined) {
    lines.push(`      body: ${typedBodies.get(route) ?? "unknown"};`);
  }

  lines.push("      response: unknown;");
  lines.push("    };");
};
