/**
 * Bash completion script for ignex.
 *
 * Registers a `complete` handler that forwards the live `COMP_LINE`/`COMP_POINT`
 * to `ignex _complete` and renders the results via `compgen`. `-o default` makes
 * bash fall back to filename completion whenever nothing matches.
 */
export const bashCompletionScript = `# bash completion for ignex
# Generated by \`ignex completions bash\`. Enable by appending to ~/.bashrc:
#   echo 'source <(ignex completions bash)' >> ~/.bashrc

_ignex_completions() {
  local cur out
  cur="\${COMP_WORDS[COMP_CWORD]}"
  out="$(ignex _complete --line "$COMP_LINE" --cursor "$COMP_POINT" 2>/dev/null)"
  COMPREPLY=( $(compgen -W "$out" -- "$cur") )
}

complete -o bashdefault -o default -F _ignex_completions ignex
`;
