/**
 * cmd.exe completion script for ignex, via clink.
 *
 * cmd.exe has no native completion hook, so this ships a clink
 * (https://github.com/chrisant996/clink) Lua matcher. The live line is written
 * to a temp file and passed with the `@file` response-file convention so cmd
 * quoting can never corrupt it.
 */
export const cmdCompletionScript = `-- clink completion for ignex (cmd.exe)
-- Generated by \`ignex completions cmd\`. Requires clink:
--   https://github.com/chrisant996/clink
-- Save as %USERPROFILE%\\clink\\ignex.lua and restart cmd.exe.

clink.argmatcher("ignex")
    :addarg(function(word, word_index, line_state)
        local out = {}
        local tmp = os.tmpname()
        local fh = assert(io.open(tmp, "w"))
        fh:write(line_state:getline())
        fh:close()

        local pipe = io.popen(
            'ignex _complete --line "@' .. tmp .. '" --cursor ' .. tostring(line_state:getcursor()),
            "r"
        )
        if pipe then
            for match in pipe:lines() do
                out[#out + 1] = match
            end
            pipe:close()
        end
        os.remove(tmp)
        return out
    end)
    :loop(1)
`;
