/**
 * Fish completion script for ignex.
 *
 * Registers a dynamic `complete -a` that forwards the full buffer and cursor to
 * `ignex _complete`. `-f` is deliberately omitted so fish keeps offering file
 * completion for paths.
 */
export const fishCompletionScript = `# fish completion for ignex
# Generated by \`ignex completions fish\`. Enable by appending to
# ~/.config/fish/config.fish:
#   ignex completions fish | source

complete -c ignex -a '(ignex _complete --line (commandline -b) --cursor (commandline -C))'
`;
