/**
 * PowerShell completion script for ignex.
 *
 * A native `Register-ArgumentCompleter` following the official .NET CLI
 * pattern: forwards the raw command text and cursor to `ignex _complete` and
 * wraps each suggestion in a `CompletionResult`.
 */
export const powershellCompletionScript = `# PowerShell completion for ignex
# Generated by \`ignex completions powershell\`. Add to your profile:
#   ignex completions powershell | Out-File -Append $PROFILE
# then reload with: . $PROFILE

Register-ArgumentCompleter -Native -CommandName ignex -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $suggestions = & ignex _complete --line $commandAst.ToString() --cursor $cursorPosition 2>$null

  $suggestions | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`;
