/**
 * Zsh completion script for ignex.
 *
 * A `#compdef` function that forwards `$BUFFER`/`$CURSOR` to `ignex _complete`
 * and feeds the results to `compadd`, falling back to `_files` for paths.
 */
export const zshCompletionScript = `#compdef ignex
# zsh completion for ignex
# Generated by \`ignex completions zsh\`. Add this file to your $fpath and run
# compinit (or source it directly):
#   source <(ignex completions zsh)

_ignex() {
  local -a suggestions
  suggestions=("\${(@f)$(ignex _complete --line "$BUFFER" --cursor "$CURSOR" 2>/dev/null)}")
  if (( \${#suggestions} )); then
    compadd -- $suggestions
  else
    _files
  fi
}

compdef _ignex ignex
`;
