/**
 * @fileoverview Published-client registry for the debugbar — tracks the SDK
 * packages (TypeScript / OpenAPI / FlatBuffers frontend client) that were
 * generated by `ignex sdk` and distributed through git tags / npm / GitHub
 * releases, so the dashboard can show "what is published, where, and how".
 *
 * Two sources of truth are combined:
 *
 * - **Local artifacts** — package directories / `package.json` / `sdk.json`
 *   files probed via `debugbar({ sdkPaths, clientPaths })`. These report the
 *   package name, version and file list on this machine.
 * - **Git tags** — `git for-each-ref refs/tags` (one process, cached) filtered
 *   by a tag prefix (`sdk-v` by default). A client whose local version has a
 *   matching tag is "tagged" — i.e. pushed to the repository — which is the
 *   release signal the `ignex sdk` flow uses.
 *
 * npm-registry state is deliberately NOT probed from the dashboard (it would
 * add a network round-trip to every panel render); the CLI/scripts report it.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";

/** A published client package (SDK platform or frontend client). */
export interface PublishedClient {
  /** `sdk` for API SDK platforms, `client` for frontend clients. */
  readonly kind: "sdk" | "client";
  /** Platform id (`typescript`, `openapi`, `flatbuffers`) or null. */
  readonly platform: string | null;
  /** npm package name. */
  readonly name: string;
  /** Local package version. */
  readonly version: string;
  /** Absolute path of the probed package.json / sdk.json. */
  readonly location: string;
  /** Files the package ships (capped at 12 for display). */
  readonly files: string[];
  /** Git tags matching the tag prefix, newest first. */
  readonly gitTags: readonly string[];
  /** Latest matching tag, or null. */
  readonly latestTag: string | null;
  /** `tagged` = a git tag exists for this package (version match or any). */
  readonly published: "tagged" | "local" | "unknown";
}

/** A parsed git tag with its creator date. */
export interface GitTagInfo {
  readonly tag: string;
  readonly date: string | null;
}

/** Options for {@link ClientRegistry}. */
export interface ClientRegistryOptions {
  /** Git tag prefixes to track, e.g. `["sdk-v"]`. Default `["sdk-v"]`. */
  readonly tagPrefixes?: readonly string[];
  /** Git working directory (default: process.cwd()). */
  readonly cwd?: string;
  /** Tag cache TTL ms (default 30s — the dashboard refreshes often). */
  readonly cacheMs?: number;
}

/** Default tag prefix — matches `ignex sdk --tag-prefix sdk-v`. */
const DEFAULT_TAG_PREFIXES = ["sdk-v"] as const;

/** Capped file list shown in the UI. */
const FILES_CAP = 12;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * Registry that combines local SDK/client probes with cached git-tag state.
 */
export class ClientRegistry {
  private readonly prefixes: readonly string[];
  private readonly cwd: string;
  private readonly cacheMs: number;
  private tagsCache: { at: number; tags: GitTagInfo[] } | null = null;
  private lastError: string | null = null;

  constructor(options: ClientRegistryOptions = {}) {
    this.prefixes = options.tagPrefixes ?? DEFAULT_TAG_PREFIXES;
    this.cwd = options.cwd ?? process.cwd();
    this.cacheMs = options.cacheMs ?? 30_000;
  }

  /** Last git error (best-effort diagnostics for the dashboard). */
  get error(): string | null {
    return this.lastError;
  }

  /**
   * List the published clients found under the probe paths.
   *
   * @param paths - Each entry is a directory containing `package.json`, the
   *   path to a `package.json` itself, or a `sdk.json` metadata file.
   */
  list(paths: readonly string[]): PublishedClient[] {
    const tags = this.gitTags();
    const clients: PublishedClient[] = [];
    for (const raw of paths) {
      if (!raw) continue;
      const probe = this.probe(raw);
      if (probe === null) continue;
      const matching = tags.filter((t) => this.prefixes.some((p) => t.tag.startsWith(p)));
      const latestTag = matching[0]?.tag ?? null;
      clients.push({
        kind: probe.kind,
        platform: probe.platform,
        name: probe.name,
        version: probe.version,
        location: probe.location,
        files: probe.files,
        gitTags: matching.map((t) => t.tag),
        latestTag,
        published: latestTag !== null ? "tagged" : "local",
      });
    }
    // Deterministic order: sdk platforms first, then clients, then by name.
    return clients.sort((a, b) => {
      if (a.kind !== b.kind) return a.kind === "sdk" ? -1 : 1;
      const byName = a.name.localeCompare(b.name);
      if (byName !== 0) return byName;
      return (a.platform ?? "").localeCompare(b.platform ?? "");
    });
  }

  /** Git tags matching the configured prefixes, newest first (cached). */
  gitTags(): GitTagInfo[] {
    const now = Date.now();
    if (this.tagsCache !== null && now - this.tagsCache.at < this.cacheMs) {
      return this.tagsCache.tags;
    }
    const tags = this.readGitTags();
    this.tagsCache = { at: now, tags };
    return tags;
  }

  /** Force-refresh the git-tag cache (used by `/api/clients?refresh=1`). */
  refresh(): void {
    this.tagsCache = null;
  }

  private readGitTags(): GitTagInfo[] {
    // One git call returns every tag with its creator date (ISO 8601).
    const result = spawnSync(
      "git",
      ["for-each-ref", "refs/tags", "--format=%(refname:short)%09%(creatordate:iso8601)"],
      { cwd: this.cwd, encoding: "utf8", timeout: 5000 },
    );
    if (result.status !== 0 || result.error !== undefined) {
      this.lastError =
        result.error?.message ?? result.stderr?.trim()?.split("\n")[0] ?? "git unavailable";
      return [];
    }
    this.lastError = null;
    const all: GitTagInfo[] = [];
    for (const line of result.stdout.split("\n")) {
      if (!line) continue;
      const [tag, date] = line.split("\t");
      if (tag === undefined) continue;
      if (this.prefixes.some((p) => tag.startsWith(p))) {
        all.push({ tag, date: date ?? null });
      }
    }
    // Newest first by date (fall back to tag order).
    return all.sort((a, b) => {
      if (a.date !== null && b.date !== null) return b.date.localeCompare(a.date);
      return a.tag.localeCompare(b.tag);
    });
  }

  /** Resolve one probe path to a client descriptor (or null). */
  private probe(path: string): {
    kind: "sdk" | "client";
    platform: string | null;
    name: string;
    version: string;
    location: string;
    files: string[];
  } | null {
    try {
      const stat = statSyncSafe(path);
      if (stat == null) return null;

      if (stat.isDirectory()) {
        const pkgPath = joinSafe(path, "package.json");
        const pkg = readJsonSafe(pkgPath);
        if (pkg === null) {
          // Maybe an sdk.json metadata file instead.
          const sdkPath = joinSafe(path, "sdk.json");
          const sdk = readJsonSafe(sdkPath);
          if (sdk === null) return null;
          return this.describe("sdk.json", sdk, path);
        }
        return this.describe("package.json", pkg, pkgPath);
      }

      if (stat.isFile()) {
        if (!path.endsWith(".json")) return null;
        const doc = readJsonSafe(path);
        if (doc === null) return null;
        return this.describe(path, doc, path);
      }
      return null;
    } catch {
      return null;
    }
  }

  /** Turn a parsed probe document into a descriptor. */
  private describe(
    source: string,
    doc: Record<string, unknown>,
    location: string,
  ): {
    kind: "sdk" | "client";
    platform: string | null;
    name: string;
    version: string;
    location: string;
    files: string[];
  } | null {
    const name = typeof doc.name === "string" ? doc.name : null;
    if (name === null || name === "") return null;
    const version = typeof doc.version === "string" ? doc.version : "0.0.0";
    const files = Array.isArray(doc.files)
      ? doc.files.filter((f): f is string => typeof f === "string").slice(0, FILES_CAP)
      : [];
    // `kind` in sdk.json marks frontend clients (flatbuffers); the rest are SDKs.
    const rawKind = isRecord(doc) && doc.kind === "client" ? "client" : "sdk";
    const platform =
      typeof doc.platform === "string"
        ? doc.platform
        : source.endsWith("sdk.json")
          ? typeof doc.platform === "string"
            ? doc.platform
            : null
          : null;
    return { kind: rawKind, platform, name, version, location, files };
  }
}

/* ── tiny sync fs helpers (safe variants that never throw) ──────────── */

const statSyncSafe = (p: string): ReturnType<typeof statSync> | null => {
  try {
    return statSync(p);
  } catch {
    return null;
  }
};

const readJsonSafe = (p: string): Record<string, unknown> | null => {
  try {
    const parsed = JSON.parse(readFileSync(p, "utf8")) as unknown;
    return isRecord(parsed) ? parsed : null;
  } catch {
    return null;
  }
};

const joinSafe = (a: string, b: string): string => join(a, b);
