/**
 * `--db sql` (Drizzle) scaffolding — the standard SQL approach wrapped with the
 * same CLI surface as the ninox Mongo path.
 *
 *   ignex resource User --db sql --fields "email:string,age:integer"
 *
 * Emits:
 *   src/models/<plural>.ts        drizzle schema tables (sqlite, bun:sqlite)
 *   src/db-sql.ts                 the drizzle client (lazy)
 *   drizzle.config.ts             drizzle-kit config (migrations via bun:sqlite)
 *   src/routes/api/<plural>/*.ts  CRUD routes over drizzle queries
 *
 * Field DSL mapping (same DSL as `ignex model`):
 *   string            → text
 *   string(format email) → text (validated at the route)
 *   string(min/max N) → text
 *   integer           → integer
 *   number            → real
 *   boolean           → integer({ mode: "boolean" })
 *   date              → integer({ mode: "timestamp_ms" })
 *   objectId          → text (stored as a 24-hex string)
 *   array(x)          → text (JSON-encoded)
 *   enum(a,b,c)       → text (validated at the route)
 *   any               → text
 */
import { type ModelField, pluralize } from "./model.js";

/** The snake_case SQL column name for a field (kebab/camel → snake). */
export const sqlColumnName = (name: string): string =>
  name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/-/g, "_")
    .toLowerCase();

/** Map one model field → a drizzle column line. */
export const drizzleColumn = (field: ModelField): string => {
  const col = sqlColumnName(field.line.split(":")[0]?.trim() ?? "field");
  const spec = field.spec ?? "string";
  const s = spec.trim();

  if (s === "integer") return `${col}: integer("${col}"),`;
  if (s === "number") return `${col}: real("${col}"),`;
  if (s === "boolean") return `${col}: integer("${col}", { mode: "boolean" }),`;
  if (s === "date") return `${col}: integer("${col}", { mode: "timestamp_ms" }),`;
  if (s === "objectId") return `${col}: text("${col}"),`;
  if (s === "any") return `${col}: text("${col}"),`;
  if (/^enum\(/.test(s)) return `${col}: text("${col}"),`;
  if (/^array\(/.test(s)) return `${col}: text("${col}"),`;
  return `${col}: text("${col}"),`; // string + string(format/min/max)
};

/** `src/models/<plural>.ts` — a drizzle sqlite table from the field DSL. */
export const drizzleModelTemplate = (name: string, fields: ModelField[]): string => {
  const plural = pluralize(name);
  const Type = name.charAt(0).toUpperCase() + name.slice(1);
  const columns = fields.map((f) => `  ${drizzleColumn(f)}`).join("\n");
  return `import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * SQL model for "${plural}" — generated by \`ignex resource ${name} --db sql\`.
 *
 * Columns map from the same field DSL as the Mongo path (text / integer /
 * real / boolean-as-integer / timestamp-ms-as-integer / JSON-encoded arrays
 * and enums as text). Dates and arrays are stored losslessly:
 *   - date      → INTEGER (unix ms) — drizzle mode timestamp_ms
 *   - array(x)  → TEXT (JSON) — decode with JSON.parse
 *   - enum(a,b) → TEXT — validated by the route's TypeBox schema
 */
export const ${plural} = sqliteTable("${plural}", {
  id: integer("id").primaryKey({ autoIncrement: true }),
${columns}
  createdAt: integer("created_at", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
});

export type ${Type} = typeof ${plural}.$inferSelect;
export type New${Type} = typeof ${plural}.$inferInsert;
`;
};

/** `src/db-sql.ts` — the shared drizzle client (lazy). */
export const drizzleDbTemplate = (): string => `import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";

// SQLite via bun:sqlite (zero-config, file-backed). Point DATABASE_URL at your
// file, e.g. DATABASE_URL=./data/app.db. For Postgres swap the driver:
//   import { drizzle } from "drizzle-orm/node-postgres";
//   export const db = drizzle(process.env.DATABASE_URL!);
const sqlite = new Database(process.env.DATABASE_URL ?? "./data/app.db");
sqlite.exec("PRAGMA journal_mode = WAL;");

export const db = drizzle(sqlite);
export { sqlite };
`;

/** `drizzle.config.ts` — drizzle-kit migrations for the generated schema. */
export const drizzleConfigTemplate = (): string => `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./src/models/*.ts",
  out: "./drizzle",
  dialect: "sqlite",
  dbCredentials: {
    url: process.env.DATABASE_URL ?? "./data/app.db",
  },
});
`;
