// biome-ignore-all lint/style/useTemplate: this module EMITS code — the
// escaped `\u0060`/`\u0024` sequences deliberately produce literal backtick /
// `$` text in the generated factory so its own `${…}` interpolations survive.
/**
 * `ignex factory` templates — test-data factory generation for ninox models.
 *
 * The factory reuses the SAME field DSL as `ignex model` (`parseModelFields`)
 * so `ignex factory User --fields "..."` always matches the model's fields.
 * Each field type maps to a randomized value generator:
 *
 *   string            → "field-<n>"             (unique per call)
 *   string(format email) → "user<n>@example.com"
 *   string(format uuid)  → a random UUID v4
 *   string(min/max N)    → a random string of the right length
 *   integer          → a random int in [-1000, 1000]
 *   number           → a random float (2 decimals)
 *   boolean          → alternating true/false (deterministic-ish per call)
 *   date             → now ± up to a year
 *   objectId         → a random 24-hex ObjectId string
 *   array(x)         → 1–3 random items of the item type
 *   enum(a,b,c)      → a random member
 *   any              → a generic string
 *
 * Optional fields are generated too (a factory always returns a full doc);
 * override anything with `{ ...makeUser(), role: "admin" }`.
 */
import { pluralize } from "./model.js";

/** One randomized value expression for a model field spec. */
export const valueExpr = (spec: string): string => {
  const rand = "Math.floor(Math.random() * 1000)";
  // Template literals emit the ${…} TEXT via escaped `\${` while interpolating
  // `rand` — so the GENERATED factory string keeps its own interpolation intact.
  const tpl = (inner: string): string => "\u0060" + inner + "\u0060";
  const s = spec.trim();

  if (!s || s === "string") return tpl("field-\u0024{" + rand + "}");

  // string(format email|uuid) / string(min N) / string(max N)
  const stringMatch = /^string(?:\s*\(\s*(.+?)\s*\))?$/.exec(s);
  if (stringMatch) {
    const opts = stringMatch[1]?.trim();
    if (!opts) return tpl("field-\u0024{" + rand + "}");
    if (opts.includes("email")) return tpl("user\u0024{" + rand + "}@example.com");
    if (opts.includes("uuid")) return "crypto.randomUUID()";
    const min = /min(\d+)/.exec(opts)?.[1];
    const max = /max(\d+)/.exec(opts)?.[1];
    const lo = min ? Number(min) : 1;
    const hi = max ? Number(max) : lo + 8;
    return `Array.from({ length: ${lo} + ${rand} % ${Math.max(1, hi - lo)} }, () => "x").join("")`;
  }

  if (s === "integer") return `${rand} - 500`;
  if (s === "number") return `Number((${rand} / 17.3).toFixed(2))`;
  if (s === "boolean") return `${rand} % 2 === 0`;
  if (s === "date") return "new Date(Date.now() + Math.floor(Math.random() * 31536000000))";
  if (s === "objectId")
    return `Array.from({ length: 24 }, () => "0123456789abcdef"[Math.floor(Math.random() * 16)]).join("")`;
  if (s === "any") return `"value-${rand}"`;

  // array(x) — 1–3 random items of the item type.
  const arrayMatch = /^array\(\s*([a-z]+)\s*\)$/.exec(s);
  if (arrayMatch) {
    const item = valueExpr(arrayMatch[1] ?? "string");
    return `Array.from({ length: 1 + ${rand} % 3 }, () => ${item})`;
  }

  // enum(a,b,c) — a random member.
  const enumMatch = /^enum\(\s*([^)]+)\s*\)$/.exec(s);
  if (enumMatch) {
    const members = (enumMatch[1] ?? "")
      .split(",")
      .map((m) => m.trim().replace(/^['"]|['"]$/g, ""))
      .filter(Boolean);
    const quoted = (members.length ? members : ["a", "b"]).map((m) => JSON.stringify(m));
    return `[${quoted.join(", ")}][Math.floor(Math.random() * ${quoted.length})]`;
  }

  return tpl("field-\u0024{" + rand + "}");
};

/** The `src/factories/<plural>.ts` module. */
export const factoryTemplate = (
  name: string,
  fields: Array<{ line: string; spec?: string }>,
): string => {
  const plural = pluralize(name);
  const Type = name.charAt(0).toUpperCase() + name.slice(1);
  const lines = fields
    .map((f) => {
      const fieldName = f.line.split(":")[0]?.trim() ?? "field";
      const spec = f.spec ?? "string";
      return `  ${fieldName}: ${valueExpr(spec)},`;
    })
    .join("\n");

  return `/**
 * Test-data factory for the "${plural}" model.
 *
 * Generated by \`ignex factory ${name}\`. Use it in tests and seeds:
 *   import { make${Type} } from "./factories/${plural}.js";
 *
 *   const doc = make${Type}();                       // all fields randomized
 *   const admin = { ...make${Type}(), role: "admin" }; // override anything
 *
 * Requires \`bun add @ignex/ninox\` (the model lives in src/models).
 */
import crypto from "node:crypto";

/** Generate one randomized ${plural} document. */
export function make${Type}(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
${lines}
    ...overrides,
  };
}

/** Generate \`count\` randomized ${plural} documents. */
export function makeMany${Type}(count = 5): Array<Record<string, unknown>> {
  return Array.from({ length: count }, () => make${Type}());
}

/** Seed \`count\` documents via the generated db handle (imported lazily). */
export async function seed${Type}(count = 5, overrides: Record<string, unknown> = {}): Promise<unknown> {
  const { db } = await import("../db.js");
  const docs = Array.from({ length: count }, () => make${Type}(overrides));
  return db.insertMany("${plural}", docs);
}
`;
};
