/**
 * @fileoverview `ignex ops caddy` template — a Caddyfile that terminates TLS
 * and proxies to the ignex backend. Pure function, split out of `./ops.ts`
 * (which re-exports it).
 */

export interface CaddyfileOptions {
  /** Site domains (default ["example.com"]). */
  domains?: string[];
  /** Backend upstream host:port (default "127.0.0.1:3000"). */
  upstream?: string;
}

/** Optimized Caddyfile — TLS termination + HSTS in front of the ignex backend. */
export function caddyfileTemplate(options: CaddyfileOptions = {}): string {
  const domains = options.domains && options.domains.length > 0 ? options.domains : ["example.com"];
  const upstream = options.upstream ?? "127.0.0.1:3000";
  const site = domains.join(", ");

  return `# Caddyfile generated by \`ignex ops caddy\` — reverse proxy for an ignex backend.
#
# Optimizations:
#   - Caddy terminates TLS (auto Let's Encrypt) and serves HTTP/2 + HTTP/3.
#   - The app already sends its security headers (CSP, COEP/COOP, ...) via
#     \`server.headers\`; HSTS is deliberately NOT set by the app (it belongs at
#     the TLS terminator), so we add it here.
#   - No \`encode gzip\`: the app compresses via its \`compression()\` plugin, so
#     re-compressing here would waste CPU.
#   - WebSockets / SSE (e.g. the /jobs and /session routes) pass through
#     automatically — Caddy upgrades them by default.

${site} {
	# Host → backend. Change to the service name when the backend runs in the
	# same compose network (e.g. app:3000).
	reverse_proxy ${upstream}

	header {
		# HSTS — only ever sent over HTTPS (Caddy is the TLS terminator).
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
	}
}
`;
}
