/**
 * @fileoverview `ignex ops ci` template — a GitHub Actions workflow (quality
 * gate + optional image build/push/deploy). Pure function, split out of
 * `./ops.ts` (which re-exports it).
 */

export interface CiWorkflowOptions {
  /**
   * Container registry image. Defaults to `ghcr.io/<owner>/<repo>` (the
   * `github.repository` expression). Only used by the deploy job (main only).
   */
  image?: string;
  /** Deploy host (`user@host`) reached over SSH — omit for build/push only. */
  deployHost?: string;
  /** Remote directory holding `docker-compose.yml` (default `/opt/ignex-app`). */
  deployDir?: string;
}

/**
 * GitHub Actions workflow — CI gate + (optional) image build/push/deploy.
 *
 * The `quality` job mirrors the framework's own gate: install → typecheck →
 * lint → test → AOT build. The scaffolded `test` boots the compiled server, so
 * the test step doubles as the smoke check. The `deploy` job runs only on
 * `main`, builds + pushes a Docker image, and (when a deploy host is given)
 * sshs in to `docker compose pull && up -d` using the files from
 * `ignex ops docker`. Requires a `DEPLOY_SSH_KEY` repo secret when deploying.
 */
export function ciWorkflowTemplate(options: CiWorkflowOptions = {}): string {
  // biome-ignore lint/suspicious/noTemplateCurlyInString: literal GitHub Actions expression
  const image = options.image ?? "ghcr.io/${{ github.repository }}";
  const deployHost = options.deployHost ?? "";
  const deployDir = options.deployDir ?? "/opt/ignex-app";

  const [userRaw, hostRaw] = deployHost.includes("@")
    ? deployHost.split("@")
    : [undefined, deployHost];
  const user = userRaw ?? "root";
  const host = hostRaw ?? "";

  const deploySteps =
    host.length > 0
      ? `
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${host}
          username: ${user || "root"}
          key: \${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${deployDir}
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
`
      : "";

  return `# Generated by \`ignex ops ci\` — CI/CD for an ignex backend.
# Requires repo secrets when deploying: DEPLOY_SSH_KEY.
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality gates
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-\${{ runner.os }}-\${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-\${{ runner.os }}-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

      - name: Lint (biome)
        run: bun run lint

      - name: Build (AOT compile)
        run: bun run build

      - name: Test (boots the compiled server)
        run: bun run test

  deploy:
    name: Build image + deploy
    if: github.ref == 'refs/heads/main'
    needs: quality
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build (AOT compile)
        run: bun run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${image}
          cache-from: type=gha
          cache-to: type=gha,mode=max
${deploySteps}
`;
}
