import type { Feature } from "../types.js";

export interface ProjectTemplateOptions {
  name: string;
  runtime: "bun" | "node";
  pm: string;
  features: Set<Feature>;
}

const PLUGIN_FEATURES: Feature[] = ["cors", "rateLimit", "security", "compression", "logger"];

export function hasPluginFeatures(features: Set<Feature>): boolean {
  return PLUGIN_FEATURES.some((feature) => features.has(feature));
}

export function packageJsonTemplate(opts: ProjectTemplateOptions): string {
  const safeName =
    opts.name
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "ignus-app";

  const dependencies: Record<string, string> = {
    "@ignus/core": "latest",
  };

  if (opts.features.has("examples")) {
    dependencies["@sinclair/typebox"] = "latest";
  }

  const devDependencies: Record<string, string> = {
    "@ignus/cli": "latest",
    "@biomejs/biome": "^2.5.5",
    oxlint: "^1.74.0",
    typescript: "^7.0.2",
  };

  if (opts.runtime === "bun") {
    devDependencies["@types/bun"] = "^1.3.14";
  } else {
    devDependencies["@types/node"] = "latest";
  }

  if (opts.features.has("openapi")) {
    devDependencies["@hey-api/openapi-ts"] = "^0.99.0";
  }

  if (opts.features.has("tests")) {
    devDependencies.vitest = "^4.1.10";
    devDependencies["@vitest/ui"] = "^4.1.10";
  }

  const scripts: Record<string, string> = {
    dev: "ignus dev",
    build: "ignus build",
    start: `${opts.runtime === "bun" ? "bun" : "node"} .ignus/server.js`,
    route: "ignus route",
    lint: "biome check .",
    format: "biome format --write .",
    typecheck: "tsc --noEmit",
  };

  if (opts.features.has("tests")) {
    scripts.test = "vitest run";
  }

  const pkg = {
    name: safeName,
    private: true,
    type: "module",
    scripts,
    dependencies,
    devDependencies,
  };

  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function tsconfigTemplate(opts: ProjectTemplateOptions): string {
  const tsconfig = {
    compilerOptions: {
      target: "ESNext",
      module: "ESNext",
      moduleResolution: "bundler",
      lib: ["ESNext"],
      strict: true,
      noUncheckedIndexedAccess: true,
      verbatimModuleSyntax: true,
      skipLibCheck: true,
      noEmit: true,
      types: opts.runtime === "bun" ? ["bun"] : ["node"],
    },
    include: ["src", "test", "ignus.config.ts", "ignus.config.mjs"],
  };

  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

export function ignusConfigTemplate(): string {
  return `/** @type {import("@ignus/compiler").CompilerOptions} */
export default {
  routesDir: "src/routes",
  hooksDir: "src/hooks",
  outDir: ".ignus",
  outFile: "server.js",

  // Production optimization profile — matches the framework's tuned example
  // (packages/app/builder.ts). Explicit knobs below can be overridden.
  optimizationLevel: 3,
  minify: false,
  sourceMap: false,

  generateTypes: true,
  generateOpenAPI: true,
  generateClient: true,

  specializeContext: true,
  hoistConstants: true,
  treeshakeRuntime: true,
  routeCache: true,

  precompileValidators: true,
  precompileSerializers: true
};
`;
}
export function biomeTemplate(): string {
  const biome = {
    $schema: "https://biomejs.dev/schemas/2.5.5/schema.json",
    organizeImports: {
      enabled: true,
    },
    linter: {
      enabled: true,
    },
    formatter: {
      enabled: true,
      indentStyle: "space",
    },
  };

  return `${JSON.stringify(biome, null, 2)}\n`;
}

export function gitignoreTemplate(): string {
  return `node_modules
.ignus
dist
coverage
*.log
.env
.DS_Store
`;
}

export function readmeTemplate(opts: ProjectTemplateOptions): string {
  const features = [...opts.features].join(", ") || "none";

  return `# ${opts.name}

Generated by @ignus/cli.

## Features

${features}

## Scripts

- \`${opts.pm} run dev\` - build, watch, and restart the generated server
- \`${opts.pm} run build\` - compile the app
- \`${opts.pm} run start\` - run the compiled server
- \`${opts.pm} run route -- products/[id].get\` - scaffold a route

## Hello World

Routes are files under \`src/routes\`; the path and method come from the filename.
The handler can be exported as a default **or** a named binding:

\`\`\`ts
// src/routes/hello.get.ts → GET /hello
export default get(() => "Hello World");
\`\`\`

\`\`\`ts
// src/routes/hello.get.ts → GET /hello (same route, named export)
export const httpGet = get(() => "Hello World");
\`\`\`

Both compile to the same fast \`Bun.serve\` route table.

## Routes

Routes live in \`src/routes\`.

Examples:

- \`src/routes/index.get.ts\` → \`GET /\`
- \`src/routes/health.get.ts\` → \`GET /health\`
- \`src/routes/products/[id].get.ts\` → \`GET /products/:id\`
`;
}

export function pluginsTemplate(opts: ProjectTemplateOptions): string {
  const selected = PLUGIN_FEATURES.filter((feature) => opts.features.has(feature));
  const calls = selected.map((feature) => `${feature}()`);

  if (calls.length === 0) {
    return `export const plugins: never[] = [];\n`;
  }

  // Emit an ARRAY (not composePlugins(...)) — the compiler and
  // pluginsToLifeCycle iterate the plugins array; a composed single object is
  // non-iterable and would crash at build time.
  return `import { ${selected.join(", ")} } from "@ignus/core";

export const plugins = [
  ${calls.join(",\n  ")}
];
`;
}
