import type { Feature } from "../types.js";

export interface ProjectTemplateOptions {
  name: string;
  runtime: "bun" | "node";
  pm: string;
  features: Set<Feature>;
}

const PLUGIN_FEATURES: Feature[] = [
  "cors",
  "rateLimit",
  "security",
  "compression",
  "logger",
];

export function hasPluginFeatures(features: Set<Feature>): boolean {
  return PLUGIN_FEATURES.some((feature) => features.has(feature));
}

export function packageJsonTemplate(opts: ProjectTemplateOptions): string {
  const safeName =
    opts.name
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "flux-app";

  const dependencies: Record<string, string> = {
    "@flux/core": "latest",
  };

  if (opts.features.has("examples")) {
    dependencies["@sinclair/typebox"] = "latest";
  }

  const devDependencies: Record<string, string> = {
    "@flux/cli": "latest",
    "@biomejs/biome": "^2.5.5",
    oxlint: "^1.74.0",
    typescript: "^7.0.2",
  };

  if (opts.runtime === "bun") {
    devDependencies["@types/bun"] = "^1.3.14";
  } else {
    devDependencies["@types/node"] = "latest";
  }

  if (opts.features.has("openapi")) {
    devDependencies["@hey-api/openapi-ts"] = "^0.99.0";
  }

  if (opts.features.has("tests")) {
    devDependencies["vitest"] = "^4.1.10";
    devDependencies["@vitest/ui"] = "^4.1.10";
  }

  const scripts: Record<string, string> = {
    dev: "flux dev",
    build: "flux build",
    start: `${opts.runtime === "bun" ? "bun" : "node"} .flux/server.js`,
    route: "flux route",
    lint: "biome check .",
    format: "biome format --write .",
    typecheck: "tsc --noEmit",
  };

  if (opts.features.has("tests")) {
    scripts.test = "vitest run";
  }

  const pkg = {
    name: safeName,
    private: true,
    type: "module",
    scripts,
    dependencies,
    devDependencies,
  };

  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function tsconfigTemplate(opts: ProjectTemplateOptions): string {
  const tsconfig = {
    compilerOptions: {
      target: "ESNext",
      module: "ESNext",
      moduleResolution: "bundler",
      lib: ["ESNext"],
      strict: true,
      noUncheckedIndexedAccess: true,
      verbatimModuleSyntax: true,
      skipLibCheck: true,
      noEmit: true,
      types: opts.runtime === "bun" ? ["bun"] : ["node"],
    },
    include: ["src", "test", "flux.config.ts", "flux.config.mjs"],
  };

  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

export function fluxConfigTemplate(): string {
  return `/** @type {import("@flux/compiler").CompilerOptions} */
export default {
  routesDir: "src/routes",
  hooksDir: "src/hooks",
  outDir: ".flux",
  outFile: "server.js"
};
`;
}
export function biomeTemplate(): string {
  const biome = {
    $schema: "https://biomejs.dev/schemas/2.5.5/schema.json",
    organizeImports: {
      enabled: true,
    },
    linter: {
      enabled: true,
    },
    formatter: {
      enabled: true,
      indentStyle: "space",
    },
  };

  return `${JSON.stringify(biome, null, 2)}\n`;
}

export function gitignoreTemplate(): string {
  return `node_modules
.flux
dist
coverage
*.log
.env
.DS_Store
`;
}

export function readmeTemplate(opts: ProjectTemplateOptions): string {
  const features = [...opts.features].join(", ") || "none";

  return `# ${opts.name}

Generated by @flux/cli.

## Features

${features}

## Scripts

- \`${opts.pm} run dev\` - build, watch, and restart the generated server
- \`${opts.pm} run build\` - compile the app
- \`${opts.pm} run start\` - run the compiled server
- \`${opts.pm} run route -- products/[id].get\` - scaffold a route

## Routes

Routes live in \`src/routes\`.

Examples:

- \`src/routes/index.get.ts\` → \`GET /\`
- \`src/routes/health.get.ts\` → \`GET /health\`
- \`src/routes/products/[id].get.ts\` → \`GET /products/:id\`
`;
}

export function pluginsTemplate(opts: ProjectTemplateOptions): string {
  const selected = PLUGIN_FEATURES.filter((feature) => opts.features.has(feature));

  const names = selected.map((feature) => feature);
  const calls = selected.map((feature) => `${feature}()`);

  return `import { composePlugins, ${names.join(", ")} } from "@flux/core";

export const plugins = composePlugins(
  ${calls.join(",\n  ")}
);
`;
}