// Auto-generated by Ignus AOT compiler.
import type { IgnusRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnusRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnusClient = {
  [Path in keyof IgnusRoutes]: {
    [Method in keyof IgnusRoutes[Path]]: IgnusRouteHandler<IgnusRoutes[Path][Method]>;
  };
};

export declare function createApiClient(baseUrl?: string, init?: RequestInit): IgnusClient;
