// Auto-generated by Ignus AOT compiler.
import { createClient } from "@ignus/core";
import type { IgnusRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnusRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnusClient = {
  [Path in keyof IgnusRoutes]: {
    [Method in keyof IgnusRoutes[Path]]: IgnusRouteHandler<IgnusRoutes[Path][Method]>;
  };
};

const ROUTES: Record<string, string> = {
  "get /": "/",
  "get /products/:id": "/products/:id",
  "post /echo": "/echo",
  "post /submit/:id": "/submit/:id",
};

// Route path → call shape ("none" | "params" | "body" | "params+body").
const ROUTE_ARGS: Record<string, "none" | "params" | "body" | "params+body"> = {
  "/": "none",
  "/products/:id": "params",
  "/echo": "body",
  "/submit/:id": "params+body"
};

const buildUrl = (path: string, params?: Record<string, string | number>): string => {
  let url = path;
  for (const [key, value] of Object.entries(params ?? {})) {
    url = url
      .replace(`:${key}`, encodeURIComponent(String(value)))
      .replace(`*${key}`, encodeURIComponent(String(value)));
  }
  return url;
};

// Deep-merge per-call init over the client-wide init so a per-call header
// doesn't clobber headers set on `createApiClient` (shallow spread would).
const mergeInit = (base: RequestInit | undefined, per: RequestInit | undefined): RequestInit => {
  const out: RequestInit = { ...base, ...per };
  if (base?.headers && per?.headers) {
    out.headers = {
      ...(base.headers as Record<string, string>),
      ...(per.headers as Record<string, string>),
    };
  }
  return out;
};

export function createApiClient(baseUrl = "", init?: RequestInit): IgnusClient {
  const client = createClient({ baseUrl });

  const routeHandler = (pathKey: string) => {
    const path = ROUTES[pathKey] ?? pathKey;
    const mode = ROUTE_ARGS[path] ?? "none";
    return new Proxy({} as Record<string, (...args: unknown[]) => Promise<unknown>>, {
      get(_, methodKey: string) {
        return async (...args: unknown[]) => {
          if (mode === "params+body") {
            const [params, body, requestInit] = args as [Record<string, string | number>, unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), body, mergeInit(init, requestInit));
          }
          if (mode === "params") {
            const [params, requestInit] = args as [Record<string, string | number>, RequestInit?];
            return client.request(methodKey.toUpperCase(), buildUrl(path, params), undefined, mergeInit(init, requestInit));
          }
          if (mode === "body") {
            const [body, requestInit] = args as [unknown, RequestInit?];
            return client.request(methodKey.toUpperCase(), path, body, mergeInit(init, requestInit));
          }
          const [requestInit] = args as [RequestInit?];
          return client.request(methodKey.toUpperCase(), path, undefined, mergeInit(init, requestInit));
        };
      },
    });
  };

  return new Proxy({} as IgnusClient, {
    get(_, pathKey: string) {
      return routeHandler(pathKey);
    },
  });
}
