// Auto-generated by Ignex AOT compiler.
import type { IgnexRoutes } from "./routes";

// Per-route call signature, derived from the route's declared params/body:
//   params+body → (params, body, init?)
//   params      → (params, init?)
//   body        → (body, init?)
//   none        → (init?)
type IgnexRouteHandler<Route> = Route extends { params: infer P; body: unknown }
  ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
  : Route extends { params: infer P }
    ? (params: P, init?: RequestInit) => Promise<unknown>
    : Route extends { body: unknown }
      ? (body: unknown, init?: RequestInit) => Promise<unknown>
      : (init?: RequestInit) => Promise<unknown>;

export type IgnexClient = {
  [Path in keyof IgnexRoutes]: {
    [Method in keyof IgnexRoutes[Path]]: IgnexRouteHandler<IgnexRoutes[Path][Method]>;
  };
};

export declare function createApiClient(baseUrl?: string, init?: RequestInit): IgnexClient;
