// Auto-generated by Ignex AOT compiler.
// Do not edit manually.

export interface IgnexRoutes {
  "/": {
    get: {
      response: unknown;
    };
  };
  "/products/:id": {
    get: {
      params: {
    "id": string;
  };
      response: unknown;
    };
  };
  "/echo": {
    post: {
      body: unknown;
      response: unknown;
    };
  };
  "/submit/:id": {
    post: {
      params: {
    "id": string;
  };
      body: unknown;
      response: unknown;
    };
  };
}
