// scripts/gen-ai-map.ts — regenerate docs/ai/TREE.md (AI scaffolding map).
//
// "Generated scaffolding" for agents: a fresh, machine-generated snapshot of
// the source tree + package metadata, so AI agents always know where to look
// without guessing. Run after structural changes:
//
//   bun run gen:ai-map
//
// The curated, human-written maps live in `docs/*.md` (architecture.md,
// router.md, native-acceleration.md, …) and `AGENTS.md`; this file is the
// auto-updated companion (docs/ai/TREE.md).

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");

// Directories to snapshot (relative to repo root). For a monorepo this is the
// whole workspace — packages/* get one section each.
const SNAPSHOT_DIRS = ["packages", "scripts", "docs", "bench", ".github"];

// Always skip (build output, vendored, VCS).
const SKIP = new Set([
  "node_modules",
  "target",
  "dist",
  "coverage",
  "client-dist",
  "prebuilds",
  ".git",
  ".vscode",
  ".npm-tmp-cache",
]);

function tree(dir: string, prefix = ""): string[] {
  const entries = readdirSync(dir)
    .filter((e) => !SKIP.has(e))
    .sort((a, b) => {
      const aDir = statSync(join(dir, a)).isDirectory();
      const bDir = statSync(join(dir, b)).isDirectory();
      if (aDir !== bDir) return aDir ? -1 : 1;
      return a.localeCompare(b);
    });
  const lines: string[] = [];
  entries.forEach((entry, i) => {
    const last = i === entries.length - 1;
    const p = join(dir, entry);
    const isDir = statSync(p).isDirectory();
    lines.push(`${prefix}${last ? "└─" : "├─"} ${entry}${isDir ? "/" : ""}`);
    if (isDir) {
      lines.push(...tree(p, prefix + (last ? "   " : "│  ")));
    }
  });
  return lines;
}

function pkg(dir = ROOT): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  } catch {
    return {};
  }
}

function main(): void {
  const p = pkg();
  const lines: string[] = [];
  lines.push("# TREE — generated scaffolding map");
  lines.push("");
  lines.push("> AUTO-GENERATED by `bun run gen:ai-map` (`scripts/gen-ai-map.ts`).");
  lines.push("> Do not edit by hand — regenerate after structural changes. The");
  lines.push("> curated maps live in `docs/*.md` and `AGENTS.md`.");
  lines.push("");
  lines.push(
    `- monorepo: \`${String(p.name ?? "unknown")}\` v${String(p.version ?? "?")} (private, workspaces: packages/*)`,
  );
  const scripts = (p.scripts ?? {}) as Record<string, string>;
  const scriptKeys = Object.keys(scripts);
  lines.push(
    `- root scripts (${scriptKeys.length}): \`${scriptKeys.slice(0, 12).join("`, `")}\`${scriptKeys.length > 12 ? ", …" : ""}`,
  );
  lines.push("");
  // One section per workspace package (name + version + scripts + tree).
  const pkgsDir = join(ROOT, "packages");
  if (existsSync(pkgsDir)) {
    lines.push("## packages/ (workspace)");
    lines.push("");
    for (const name of readdirSync(pkgsDir).sort()) {
      const pkgDir = join(pkgsDir, name);
      if (!statSync(pkgDir).isDirectory() || SKIP.has(name)) continue;
      const pp = pkg(pkgDir);
      const ps = (pp.scripts ?? {}) as Record<string, string>;
      lines.push(
        `### \`${String(pp.name ?? name)}\` v${String(pp.version ?? "?")}${ps.test ? ` · test: \`${ps.test}\`` : ""}`,
      );
      lines.push("");
      lines.push("```");
      lines.push(`packages/${name}/`);
      lines.push(...tree(pkgDir));
      lines.push("```");
      lines.push("");
    }
  }
  for (const dir of SNAPSHOT_DIRS.filter((d) => d !== "packages")) {
    const abs = join(ROOT, dir);
    if (!existsSync(abs)) continue;
    lines.push(`## ${dir}/`);
    lines.push("");
    lines.push("```");
    lines.push(`${dir}/`);
    lines.push(...tree(abs));
    lines.push("```");
    lines.push("");
  }
  lines.push("## Notes");
  lines.push("");
  lines.push(
    "- `SKIP` set in the script excludes build output (dist/, coverage/, node_modules/, target/).",
  );
  lines.push(
    "- For the human-written maps + architecture flows, see `docs/architecture.md` and `AGENTS.md`.",
  );
  lines.push("");

  const outDir = join(ROOT, "docs", "ai");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "TREE.md"), lines.join("\n"));
  console.log(`✓ regenerated ${relative(ROOT, join(outDir, "TREE.md"))} (${lines.length} lines)`);
}

main();
