/**
 * @fileoverview FlatBuffers frontend-client SDK platform.
 *
 * Emits an installable npm package for frontend teams that want **binary**
 * API transport: a real `.fbs` schema describing the wire envelope, a codec
 * built on the official `flatbuffers` runtime (the same runtime the
 * `@ignex/nova` realtime transport uses), and a typed client whose
 * request/response envelopes ride with the `application/x-flatbuffers`
 * content type (JSON fallback included, so the client also works against
 * vanilla JSON endpoints).
 *
 * Why an envelope + JSON strings? The compiled app's payload schemas are
 * arbitrary JSON Schema (not typed FlatBuffers tables), so the *envelope* is
 * the FlatBuffers contract — method, route template and JSON-encoded params /
 * query / body / response ride as string fields — while the payloads stay
 * exactly what the API already produces. The `.fbs` schema ships the route
 * inventory as a reflection table, so any FlatBuffers tooling can introspect
 * the API surface.
 *
 * The package depends on `flatbuffers` (^25.x) — a tiny, dependency-free
 * runtime — and is generated with the same builder/reader patterns as nova's
 * `ts-ser.ts` (strings created before `startObject`, pooled builder, offsets
 * via `__offset`/`__string`).
 */

import type { SdkFile, SdkGenerateContext, SdkPlatform, SdkRouteInfo } from "./types";
import { emitRoutesDts, emitTypesDts, hasParams } from "./typescript";

/** Route call shape used in ROUTE_ARGS + schema docs. */
type CallShape = "none" | "params" | "body" | "params+body";

const modeFor = (r: SdkRouteInfo): CallShape => {
  const params = hasParams(r);
  const body = r.usesBody;
  return params ? (body ? "params+body" : "params") : body ? "body" : "none";
};

/** Emit `schema.fbs` — the wire envelope + route inventory. */
const emitSchemaFbs = (_routes: readonly SdkRouteInfo[]): string => {
  const lines = [
    "// Auto-generated by Ignex SDK generator. Do not edit.",
    "// Wire envelope for the <serviceName> API — binary request/response",
    "// transport. Payloads ride as JSON strings inside the envelope so they",
    "// stay identical to the API's JSON contract.",
    "",
    'file_identifier "IGNA";',
    "",
    "/// One outbound API call.",
    "table Request {",
    "  method: string;       /// HTTP method (GET / POST / ...)",
    '  path: string;         /// Route template, e.g. "/products/:id"',
    "  params_json: string;  /// JSON-encoded path params",
    "  query_json: string;   /// JSON-encoded query params",
    "  body_json: string;    /// JSON-encoded request body",
    "}",
    "",
    "/// One inbound API response.",
    "table Response {",
    "  status: ushort;       /// HTTP status code",
    "  ok: bool;             /// 2xx?",
    "  error: string;        /// Error message when !ok",
    "  body_json: string;    /// JSON-encoded response payload",
    "  trace_id: string;     /// Debugbar trace id when present",
    "}",
    "",
    "/// One route in the compiled API (reflection).",
    "table RouteMeta {",
    "  method: string;",
    "  path: string;",
    '  args: string;         /// "none" | "params" | "body" | "params+body"',
    "}",
    "",
    "/// The complete route inventory.",
    "table ApiRoutes {",
    "  routes: [RouteMeta];",
    "}",
    "",
    "root_type Response;",
    "",
  ];
  return lines.join("\n");
};

/** Emit `dist/codec.js` — envelope codec on the official flatbuffers runtime. */
const emitCodecJs = (): string => `// Auto-generated by Ignex SDK generator. Do not edit.
// Envelope codec for schema.fbs, built on the official "flatbuffers" runtime
// (the same runtime @ignex/nova uses for its typed realtime transport).
// Strings are created before startObject (the builder's notNested guard).

import * as flatbuffers from "flatbuffers";

/** pooled builder — each encode clears it (safe because asUint8Array copies). */
let shared = null;
function getBuilder() {
  if (!shared) shared = new flatbuffers.Builder(1024);
  return shared;
}

function jsonOrEmpty(value) {
  if (value === undefined || value === null) return "";
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}

function parseJson(text) {
  if (!text) return undefined;
  try { return JSON.parse(text); } catch (e) { return text; }
}

/// Encode one request envelope. \`params/query/body\` are JSON-able values.
function encodeRequest({ method, path, params, query, body }) {
  const b = getBuilder();
  const sBody = b.createString(jsonOrEmpty(body));
  const sQuery = b.createString(jsonOrEmpty(query));
  const sParams = b.createString(jsonOrEmpty(params));
  const sPath = b.createString(path || "");
  const sMethod = b.createString(method || "");
  b.startObject(5);
  b.addFieldOffset(4, sBody, 0);
  b.addFieldOffset(3, sQuery, 0);
  b.addFieldOffset(2, sParams, 0);
  b.addFieldOffset(1, sPath, 0);
  b.addFieldOffset(0, sMethod, 0);
  const root = b.endObject();
  b.finish(root);
  return b.asUint8Array();
}

/// Decode a request envelope from bytes.
function decodeRequest(bytes) {
  const bb = new flatbuffers.ByteBuffer(bytes);
  const root = bb.readInt32(bb.position()) + bb.position();
  const field = (id) => {
    const o = bb.__offset(root, 4 + id * 2);
    return o === 0 ? null : bb.__string(root + o);
  };
  return {
    method: field(0) || "",
    path: field(1) || "",
    params: parseJson(field(2)),
    query: parseJson(field(3)),
    body: parseJson(field(4)),
  };
}

/// Encode a response envelope.
function encodeResponse({ status, ok, error, bodyJson, traceId }) {
  const b = getBuilder();
  const sTrace = b.createString(traceId || "");
  const sBody = b.createString(bodyJson || "");
  const sError = b.createString(error || "");
  b.startObject(5);
  b.addFieldOffset(4, sTrace, 0);
  b.addFieldOffset(3, sBody, 0);
  b.addFieldOffset(2, sError, 0);
  b.addFieldInt8(1, ok ? 1 : 0, 0);
  b.addFieldInt16(0, status, 0);
  const root = b.endObject();
  b.finish(root);
  return b.asUint8Array();
}

/// Decode a response envelope from bytes.
function decodeResponse(bytes) {
  const bb = new flatbuffers.ByteBuffer(bytes);
  const root = bb.readInt32(bb.position()) + bb.position();
  const field = (id) => {
    const o = bb.__offset(root, 4 + id * 2);
    return o === 0 ? null : bb.__string(root + o);
  };
  const status = (() => {
    const o = bb.__offset(root, 4);
    return o === 0 ? 0 : bb.readUint16(root + o);
  })();
  const ok = (() => {
    const o = bb.__offset(root, 6);
    return o === 0 ? false : bb.readUint8(root + o) !== 0;
  })();
  return {
    status,
    ok,
    error: field(2) || "",
    bodyJson: field(3) || "",
    traceId: field(4) || "",
  };
}

/// Encode the route-inventory table (reflection).
function encodeApiRoutes(routes) {
  const b = getBuilder();
  const metas = routes.map((r) => {
    const sArgs = b.createString(r.args || "none");
    const sPath = b.createString(r.path);
    const sMethod = b.createString(r.method);
    b.startObject(3);
    b.addFieldOffset(2, sArgs, 0);
    b.addFieldOffset(1, sPath, 0);
    b.addFieldOffset(0, sMethod, 0);
    return b.endObject();
  });
  // flatc pattern for a vector of tables:
  b.startVector(4, metas.length, 4);
  for (let i = metas.length - 1; i >= 0; i--) b.addOffset(metas[i]);
  const vec = b.endVector();
  b.startObject(1);
  b.addFieldOffset(0, vec, 0);
  const root = b.endObject();
  b.finish(root);
  return b.asUint8Array();
}

/// Decode the route-inventory table.
function decodeApiRoutes(bytes) {
  const bb = new flatbuffers.ByteBuffer(bytes);
  const root = bb.readInt32(bb.position()) + bb.position();
  const o = bb.__offset(root, 4);
  if (o === 0) return [];
  const vec = root + o;
  const len = bb.__vector_len(vec);
  const out = [];
  for (let i = 0; i < len; i++) {
    const table = bb.__indirect(bb.__vector(vec) + i * 4);
    const field = (id) => {
      const fo = bb.__offset(table, 4 + id * 2);
      return fo === 0 ? null : bb.__string(table + fo);
    };
    out.push({ method: field(0) || "", path: field(1) || "", args: field(2) || "none" });
  }
  return out;
}

export {
  encodeRequest, decodeRequest,
  encodeResponse, decodeResponse,
  encodeApiRoutes, decodeApiRoutes,
};
`;

/** Emit `dist/codec.d.ts`. */
const emitCodecDts = (): string => `// Auto-generated by Ignex SDK generator. Do not edit.
export interface RequestEnvelope {
  method: string;
  path: string;
  params?: unknown;
  query?: unknown;
  body?: unknown;
}
export interface ResponseEnvelope {
  status: number;
  ok: boolean;
  error: string;
  bodyJson: string;
  traceId: string;
}
export interface RouteMeta {
  method: string;
  path: string;
  args: string;
}
export declare function encodeRequest(req: RequestEnvelope): Uint8Array;
export declare function decodeRequest(bytes: Uint8Array): Required<RequestEnvelope> & { params?: unknown; query?: unknown; body?: unknown };
export declare function encodeResponse(res: Partial<ResponseEnvelope> & { status: number }): Uint8Array;
export declare function decodeResponse(bytes: Uint8Array): ResponseEnvelope;
export declare function encodeApiRoutes(routes: RouteMeta[]): Uint8Array;
export declare function decodeApiRoutes(bytes: Uint8Array): RouteMeta[];
`;

/** Emit `dist/client.js` — the typed FlatBuffers fetch client. */
const emitClientJs = (routes: readonly SdkRouteInfo[]): string => {
  const routeEntries = routes
    .map(
      (r) =>
        `  ${JSON.stringify(`${r.method.toLowerCase()} ${r.path}`)}: ${JSON.stringify(r.path)},`,
    )
    .join("\n");
  const argsEntries = routes
    .map((r) => `  ${JSON.stringify(r.path)}: ${JSON.stringify(modeFor(r))},`)
    .join("\n");

  return `// Auto-generated by Ignex SDK generator. Do not edit.
// Typed FlatBuffers client — binary request/response envelopes with a JSON
// fallback (works against vanilla JSON endpoints too).

import { encodeRequest, decodeResponse } from "./codec.js";

export class FlatBufferClientError extends Error {
  constructor(status, message, body, response) {
    super(message);
    this.name = "FlatBufferClientError";
    this.status = status;
    this.body = body;
    this.response = response;
  }
}

const ROUTES = {
${routeEntries}
};

const ROUTE_ARGS = {
${argsEntries}
};

const buildUrl = (path, params) => {
  let url = path;
  for (const [key, value] of Object.entries(params ?? {})) {
    url = url
      .replace(\`:\${key}\`, encodeURIComponent(String(value)))
      .replace(\`*\${key}\`, encodeURIComponent(String(value)));
  }
  return url;
};

const mergeInit = (base, per) => {
  const out = { ...base, ...per };
  if (base?.headers && per?.headers) {
    out.headers = { ...base.headers, ...per.headers };
  }
  return out;
};

const toQueryString = (obj) => {
  const parts = [];
  for (const [key, value] of Object.entries(obj ?? {})) {
    if (Array.isArray(value)) {
      for (const item of value) parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(item)));
    } else if (value !== undefined) {
      parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(value)));
    }
  }
  return parts.length ? "?" + parts.join("&") : "";
};

/// Parse a response body: FlatBuffer envelope first, JSON text fallback.
const parseBody = async (response) => {
  const contentType = response.headers.get("content-type") || "";
  if (contentType.includes("x-flatbuffers")) {
    const bytes = new Uint8Array(await response.arrayBuffer());
    return decodeResponse(bytes);
  }
  const text = await response.text();
  if (!text) return null;
  try { return JSON.parse(text); } catch (e) { return text; }
};

export const createFlatBufferClient = (options) => {
  const base = (options?.baseUrl ?? "").replace(/\\/+$/, "");
  const baseHeaders = options?.headers ?? {};
  const fetcher = options?.fetch ?? globalThis.fetch;
  const credentials = options?.credentials;
  const baseOptions = { headers: baseHeaders };

  const request = async (method, path, params, query, body, init) => {
    // GET/HEAD cannot carry a fetch body: encode params/query into the URL
    // (standard REST semantics) and still decode the FlatBuffer response
    // envelope. Every other method sends the envelope as the body.
    const url = buildUrl(base + path, params);
    const isBodyless = method === "GET" || method === "HEAD";
    const headers = {
      ...baseHeaders,
      accept: "application/x-flatbuffers, application/json",
      ...(init?.headers ?? {}),
    };
    let payload;
    if (isBodyless) {
      payload = undefined;
    } else {
      headers["content-type"] = "application/x-flatbuffers";
      payload = encodeRequest({ method, path, params, query, body });
    }
    const response = await fetcher(url + toQueryString(isBodyless ? { ...(params ?? {}), ...(query ?? {}) } : null), {
      ...(credentials !== undefined ? { credentials } : {}),
      ...init,
      method,
      headers,
      ...(payload !== undefined ? { body: payload } : {}),
    });
    const parsed = await parseBody(response);
    if (!response.ok) {
      const message = parsed && typeof parsed === "object" && parsed.error
        ? parsed.error
        : \`Request failed: \${response.status} \${response.statusText} \${path}\`;
      throw new FlatBufferClientError(response.status, message, parsed, response);
    }
    if (parsed && typeof parsed === "object" && parsed.bodyJson !== undefined) {
      // FlatBuffer envelope → parse the embedded JSON payload.
      try { return parsed.bodyJson ? JSON.parse(parsed.bodyJson) : null; }
      catch (e) { return parsed.bodyJson; }
    }
    return parsed;
  };

  const routeHandler = (pathKey) => {
    const path = ROUTES[pathKey] ?? pathKey;
    const mode = ROUTE_ARGS[path] ?? "none";
    return new Proxy({}, {
      get(_, methodKey) {
        return async (...args) => {
          if (mode === "params+body") {
            const [params, body, init] = args;
            return request(methodKey.toUpperCase(), path, params, undefined, body, mergeInit(baseOptions, init));
          }
          if (mode === "params") {
            const [params, init] = args;
            return request(methodKey.toUpperCase(), path, params, undefined, undefined, mergeInit(baseOptions, init));
          }
          if (mode === "body") {
            const [body, init] = args;
            return request(methodKey.toUpperCase(), path, undefined, undefined, body, mergeInit(baseOptions, init));
          }
          const [init] = args;
          return request(methodKey.toUpperCase(), path, undefined, undefined, undefined, mergeInit(baseOptions, init));
        };
      },
    });
  };

  return new Proxy({}, {
    get(_, pathKey) {
      return routeHandler(pathKey);
    },
  });
};
`;
};

/** Emit `dist/client.d.ts`. */
const emitClientDts = (): string => `// Auto-generated by Ignex SDK generator. Do not edit.
import type { IgnexClient } from "./routes";

/** Options for {@link createFlatBufferClient}. */
export interface FlatBufferClientOptions {
  /** Base URL of the API (e.g. \`https://api.example.com\`). */
  baseUrl: string;
  /** Headers applied to every request (merged under per-call headers). */
  headers?: Record<string, string>;
  /** Custom fetch implementation (defaults to the global fetch). */
  fetch?: typeof fetch;
  /** Attach credentials (\`"include"\` for cookies) to every request. */
  credentials?: RequestCredentials;
}

/** Error thrown by the generated client on non-2xx responses. */
export declare class FlatBufferClientError extends Error {
  status: number;
  body: unknown;
  response: Response;
}

/**
 * Create a fully typed FlatBuffers client for the generated routes.
 * Requests are encoded as \`application/x-flatbuffers\` envelopes; responses
 * are decoded from envelopes when the server speaks FlatBuffers, otherwise
 * JSON is parsed as a fallback.
 */
export declare function createFlatBufferClient(options: FlatBufferClientOptions): IgnexClient;
`;

/** Emit the package entry files. */
const emitIndexFiles = (): SdkFile[] => [
  {
    path: "dist/index.d.ts",
    content: `// Auto-generated by Ignex SDK generator. Do not edit.
export { createFlatBufferClient, FlatBufferClientError } from "./client";
export type { FlatBufferClientOptions } from "./client";
export type { IgnexClient, IgnexRoutes } from "./routes";
export {
  encodeRequest, decodeRequest, encodeResponse, decodeResponse,
  encodeApiRoutes, decodeApiRoutes,
} from "./codec";
export type { RequestEnvelope, ResponseEnvelope, RouteMeta } from "./codec";
`,
  },
  {
    path: "dist/index.js",
    content: `// Auto-generated by Ignex SDK generator. Do not edit.
export { createFlatBufferClient, FlatBufferClientError } from "./client.js";
export {
  encodeRequest, decodeRequest, encodeResponse, decodeResponse,
  encodeApiRoutes, decodeApiRoutes,
} from "./codec.js";
`,
  },
];

/** Emit the package `package.json` (marked kind:client for the debugbar). */
const emitPackageJson = (ctx: SdkGenerateContext): string => {
  const { options } = ctx;
  const name = options.name ?? defaultClientName(ctx);
  const version = options.version ?? "0.0.0";
  const description =
    options.description ??
    `Generated FlatBuffers frontend client for the \`${ctx.serviceName}\` API (binary envelope transport on the official flatbuffers runtime + .fbs schema).`;
  const pkg = {
    name,
    version,
    description,
    type: "module",
    sideEffects: false,
    main: "./dist/index.js",
    module: "./dist/index.js",
    types: "./dist/index.d.ts",
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
      "./schema.fbs": "./schema.fbs",
    },
    files: ["dist", "schema.fbs", "README.md"],
    dependencies: {
      // The official FlatBuffers runtime — the same dependency the
      // @ignex/nova realtime transport uses (tiny, dependency-free).
      flatbuffers: "^25.9.23",
    },
    license: options.license ?? "MIT",
    engines: { node: ">=18" },
    // Debugbar discovery metadata: the Clients panel picks up packages whose
    // package.json carries these fields (see debugbar's ClientRegistry).
    kind: "client",
    platform: "flatbuffers",
    ...(options.repoUrl !== undefined ? { repository: { type: "git", url: options.repoUrl } } : {}),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
};

/** Default package name: `<scope>/<serviceName>-flatbuffers-client`. */
const defaultClientName = (ctx: SdkGenerateContext): string => {
  const base = `${ctx.serviceName}-flatbuffers-client`;
  return ctx.options.scope !== undefined ? `${ctx.options.scope}/${base}` : base;
};

/** Emit the README. */
const emitReadme = (ctx: SdkGenerateContext): string => {
  const { options, serviceName } = ctx;
  const name = options.name ?? defaultClientName(ctx);
  const version = options.version ?? "0.0.0";
  const install =
    options.repoUrl !== undefined
      ? `npm install ${name}
# or install directly from the GitHub release tarball:
npm install ${options.repoUrl}/releases/download/sdk-v${version}/${name.replace("@", "").replace("/", "-")}-${version}.tgz`
      : `npm install ${name}`;

  const local =
    options.localInstallPath !== undefined
      ? `
## Local testing (before it is published)

Test this client straight from the generated package:

\`\`\`sh
npm install ${options.localInstallPath}
\`\`\`

As soon as the repo is available, run \`ignex sdk --platform flatbuffers --push --release\`
(or \`--publish\`) to distribute it.
`
      : "";

  return `# ${name}

Generated **FlatBuffers** frontend client for the **${serviceName}** API — binary
request/response envelopes over HTTP, with a JSON fallback.

- Built on the official **\`flatbuffers\`** runtime (the same runtime \`@ignex/nova\` uses for its typed realtime transport).
- **Typed routes** — same per-route signatures as the TypeScript SDK (params/body/query/response from OpenAPI).
- **\`schema.fbs\`** — the wire contract + route inventory, usable by any FlatBuffers tooling.
- **Content negotiation** — sends \`application/x-flatbuffers\`, falls back to JSON when the server responds with JSON.

## Install

${install}${local}

## Quick start

\`\`\`ts
import { createFlatBufferClient } from "${name}";

const api = createFlatBufferClient({ baseUrl: "https://api.example.com" });

const order = await api["/api/orders"].post({ orderId: "ord_123", quantity: 2 });
const report = await api["/api/reports/:id"].get({ id: "42" });
const me = await api["/auth/me"].get();
\`\`\`

## Wire format

Every call encodes a \`Request\` envelope (method, path, params/query/body as JSON strings)
as a FlatBuffer binary and sends it with \`content-type: application/x-flatbuffers\`.
Responses are \`Response\` envelopes (status, ok, error, body_json, trace_id). See
\`schema.fbs\` for the exact layout.

## Low-level codec

\`\`\`ts
import { encodeRequest, decodeResponse, encodeApiRoutes, decodeApiRoutes } from "${name}";

const bytes = encodeRequest({ method: "POST", path: "/api/orders", body: { qty: 2 } });
const res = decodeResponse(await fetch("https://api.example.com/api/orders", {
  method: "POST",
  headers: { "content-type": "application/x-flatbuffers" },
  body: bytes,
}).then((r) => r.arrayBuffer()));

const routes = decodeApiRoutes(apiRoutesBytes); // route inventory reflection
\`\`\`

## Publishing

\`\`\`sh
ignex sdk --platform flatbuffers --version ${version} --push          # generate + git tag sdk-v${version}
ignex sdk --platform flatbuffers --version ${version} --publish       # + publish to the npm registry
ignex sdk --platform flatbuffers --version ${version} --release       # + attach the tarball to a GitHub release
\`\`\`

The debugbar **Clients** panel tracks this package (local version + git tags) once you point
\`debugbar({ clientPaths })\` at the generated directory.
`;
};

/**
 * The FlatBuffers SDK platform: emits an installable npm package with a
 * binary-transport typed client, an envelope codec on the official
 * flatbuffers runtime and the .fbs schema.
 */
export const flatbuffersPlatform: SdkPlatform = {
  id: "flatbuffers",
  label: "FlatBuffers client",
  description:
    "Zero-dependency FlatBuffers frontend client: binary envelopes, typed routes, .fbs schema + codec.",
  generate(ctx: SdkGenerateContext): readonly SdkFile[] {
    const { routes } = ctx;
    return [
      { path: "package.json", content: emitPackageJson(ctx) },
      { path: "README.md", content: emitReadme(ctx) },
      { path: "schema.fbs", content: emitSchemaFbs(routes) },
      { path: "dist/codec.js", content: emitCodecJs() },
      { path: "dist/codec.d.ts", content: emitCodecDts() },
      { path: "dist/types.d.ts", content: emitTypesDts(routes, ctx) },
      { path: "dist/routes.d.ts", content: emitRoutesDts(routes, ctx) },
      { path: "dist/client.d.ts", content: emitClientDts() },
      { path: "dist/client.js", content: emitClientJs(routes) },
      ...emitIndexFiles(),
    ];
  },
};
