/**
 * @fileoverview OpenAPI spec SDK platform.
 *
 * A minimal "spec-only" SDK: an npm package whose single artifact is the
 * compiled `openapi.json` document. Frontend teams that already generate their
 * own clients (hey-api, orval, openapi-typescript, …) can install the spec as
 * a pinned, versioned dependency instead of copy-pasting it.
 */

import type { SdkFile, SdkGenerateContext, SdkPlatform } from "./types";

/**
 * The OpenAPI spec platform: emits an npm package containing only the
 * canonical `openapi.json` document for the compiled app.
 */
export const openapiPlatform: SdkPlatform = {
  id: "openapi",
  label: "OpenAPI spec",
  description: "Spec-only npm package: just the compiled openapi.json, versioned + installable.",
  generate(ctx: SdkGenerateContext): readonly SdkFile[] {
    const { options } = ctx;
    const name = options.name ?? defaultSpecName(ctx);
    const version = options.version ?? "0.0.0";
    const pkg = {
      name,
      version,
      description: `OpenAPI 3.1 specification for the \`${ctx.serviceName}\` API (generated by ignex).`,
      type: "module",
      main: "./openapi.json",
      exports: {
        ".": "./openapi.json",
      },
      files: ["openapi.json"],
      license: options.license ?? "MIT",
      ...(options.repoUrl !== undefined
        ? { repository: { type: "git", url: options.repoUrl } }
        : {}),
    };

    return [
      { path: "package.json", content: `${JSON.stringify(pkg, null, 2)}\n` },
      { path: "openapi.json", content: `${JSON.stringify(ctx.openapi, null, 2)}\n` },
      {
        path: "README.md",
        content: `# ${name}

OpenAPI 3.1 specification for the **${ctx.serviceName}** API, generated by ignex.

\`\`\`sh
npm install ${name}
\`\`\`

\`\`\`ts
import spec from "${name}/openapi.json" with { type: "json" };
// Feed \`spec\` into your favourite codegen (openapi-typescript, orval, …).
\`\`\`
`,
      },
    ];
  },
};

/** Default spec package name: `<scope>/<serviceName>-api-spec`. */
const defaultSpecName = (ctx: SdkGenerateContext): string => {
  const base = `${ctx.serviceName}-api-spec`;
  return ctx.options.scope !== undefined ? `${ctx.options.scope}/${base}` : base;
};
