/**
 * @fileoverview Realtime SDK platform — nova FlatBuffer wire stack + typed
 * WebSocket client + typed RPC-over-WS client.
 *
 * Derived from two build artifacts (loaded by `loadSdkInputs` into
 * `ctx.realtime`):
 *
 * - `<outDir>/realtime.json` — written by `ignex build` from the app's
 *   `src/realtime.ts` `{ subjectPrefix, schemas?, events, controlEvents? }`.
 * - `<outDir>/rpc-manifest.json` — written by the runtime RPC kit
 *   (`{ methods: { "<method.name>": <args schema> } }`).
 *
 * Emitted package:
 *
 * - `realtime/` — the generated nova wire stack (FlatBuffers schema, flatc TS
 *   decoders, registry, encoders, `makeBindings`) produced lazily via
 *   `@ignex/nova/generate`'s `generateBindings` (needs `flatc` on PATH).
 * - `realtime/schema.ts` — the input TypeBox registries as runtime consts.
 * - `realtime/payloads.gen.ts` — precise payload types per event/method.
 * - `realtime/client.gen.ts` — typed client facade over `@ignex/nova/client`.
 * - `realtime/server.ts` — typed SERVER-side facade (`emit`/`on`/`emitToUser`
 *   over the bound hub) so app code never casts custom event names.
 * - `realtime/rpc.gen.ts` — typed RPC-over-WS calls (`callRpc`, `RpcError`).
 *
 * The root barrel (`realtime/index.ts`) is intentionally BROWSER-safe: it does
 * NOT re-export `realtime/server.ts`. That facade imports `@ignex/nova/events`,
 * whose cluster/Redis loader pulls in `node:module`'s `createRequire` — code
 * that crashes any browser bundle ("createRequire is not a function"). Server
 * code must import the facade from the `<pkg>/server` subpath instead.
 *
 * The platform is otherwise pure: it returns {@link SdkFile}s from the shared
 * {@link SdkGenerateContext} and never touches the filesystem.
 */

import { jsonSchemaToTs } from "./json-schema-to-ts";
import type { SdkFile, SdkGenerateContext, SdkPlatform, SdkRealtimeInput } from "./types";

/** Runtime specifier of the optional peer codegen module. */
const NOVA_GENERATE_SPECIFIER: string = "@ignex/nova/generate";

/** Structural contract of `generateBindings`' return value (what we consume). */
interface NovaGenerated {
  /** All generated artifacts keyed by relative path (e.g. `ts/backend.ts`). */
  files: Record<string, string>;
}

/** Structural contract of the dynamically imported `@ignex/nova/generate`. */
interface NovaGenerateModule {
  generateBindings(
    schema: { schemas?: unknown; events: unknown; controlEvents?: unknown },
    options: { rust: false; ffiMode: "optional"; subjectPrefix: string; force: true },
  ): NovaGenerated;
}

/**
 * Import `@ignex/nova/generate` lazily (optional peer) with a clear error when
 * the dependency or its `flatc` prerequisite is missing.
 */
const loadNovaGenerate = async (): Promise<NovaGenerateModule> => {
  try {
    // A non-literal specifier keeps this module importable without the peer;
    // resolution (and its failure modes) happen at runtime.
    const mod = (await import(NOVA_GENERATE_SPECIFIER)) as Partial<NovaGenerateModule>;
    if (mod.generateBindings === undefined) {
      throw new Error("module has no generateBindings export");
    }
    return mod as NovaGenerateModule;
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new Error(
      `The realtime SDK platform requires the optional peer "@ignex/nova" — install it with ` +
        `\`bun add @ignex/nova\`. Codegen additionally needs the FlatBuffers compiler (\`flatc\`) on ` +
        `PATH (brew install flatbuffers / apt install flatbuffers-compiler). Import failed: ${reason}`,
    );
  }
};

/** Guard: realtime declarations must exist and declare at least one event. */
const requireRealtimeInput = (ctx: SdkGenerateContext): SdkRealtimeInput => {
  const input = ctx.realtime;
  if (input === undefined || Object.keys(input.events).length === 0) {
    throw new Error(
      `No realtime declarations for the ${ctx.serviceName} SDK — run \`ignex build\` with a ` +
        `\`src/realtime.ts\` exporting \`realtime\` ({ subjectPrefix, events, ... }); expected at ` +
        `${ctx.options.outDir}/realtime.json.`,
    );
  }
  return input;
};

/** Map a generated relative path onto its location inside the emitted package. */
const packagePathOf = (rel: string): string => {
  // The generated entry module ships as `wire.ts`; the package barrel
  // (`realtime/index.ts`) is framework-owned (emitted below).
  const renamed = rel === "index.ts" ? "wire.ts" : rel;
  return `realtime/${renamed}`;
};

/** Emit `realtime/schema.ts` — the input registries as plain-object consts. */
const emitSchemaTs = (input: SdkRealtimeInput): string => {
  const sections = {
    schemas: input.schemas ?? {},
    events: input.events,
    controlEvents: input.controlEvents ?? {},
  };
  return `// @generated by ignex sdk — DO NOT EDIT
import type { TSchema } from "@sinclair/typebox";

// The app's TypeBox registries (JSON form, serialized from <outDir>/realtime.json).
// Runtime decoding uses the generated FlatBuffer decoders; these consts feed
// makeBindings (via ./wire) and any consumer-side schema tooling. The cast is
// sound at the type boundary; payload types live in ./payloads.gen.
const raw = ${JSON.stringify(sections, null, 2)};

export const schemas = raw.schemas as unknown as Record<string, TSchema>;
export const events = raw.events as unknown as Record<string, TSchema>;
export const controlEvents = raw.controlEvents as unknown as Record<string, TSchema>;
`;
};

/** Emit `realtime/payloads.gen.ts` — payload/args types per event/method. */
const emitPayloadsGen = (input: SdkRealtimeInput): string => {
  const lines = [
    "// @generated by ignex sdk — DO NOT EDIT",
    "",
    "/** Payload type per realtime event, derived from the app's TypeBox schemas. */",
    "export type RealtimeEventPayloads = {",
  ];
  for (const name of Object.keys(input.events)) {
    lines.push(`  ${JSON.stringify(name)}: ${jsonSchemaToTs(input.events[name])};`);
  }
  lines.push("};");
  lines.push("");

  const methods = input.rpcMethods ?? {};
  lines.push("/** Args type per RPC method, derived from the runtime RPC kit manifest. */");
  lines.push("export type RpcMethodArgs = {");
  for (const name of Object.keys(methods)) {
    lines.push(`  ${JSON.stringify(name)}: ${jsonSchemaToTs(methods[name])};`);
  }
  lines.push("};");
  lines.push("");

  return lines.join("\n");
};

/** Emit `realtime/client.gen.ts` — typed facade over `@ignex/nova/client`. */
const emitClientGen = (): string => `// @generated by ignex sdk — DO NOT EDIT
import { createClient } from "@ignex/nova/client";
import type { ClientStatus, IgnClientOptions } from "@ignex/nova/client";
import type { RealtimeEventPayloads } from "./payloads.gen";
import { controlEvents, events } from "./schema";
import { makeBindings } from "./wire";

/** The app's assembled runtime bindings (typed against the app's events). */
export const bindings = makeBindings({ events, controlEvents } as never);

/** Event names this client can send/observe (derived from payloads.gen.ts). */
export type RealtimeEventName = keyof RealtimeEventPayloads & string;

/**
 * Minimal structural client surface for app code: payload-typed
 * \`on\`/\`off\`/\`once\`/\`send\`, connection lifecycle, and errors.
 * Implemented by casting the underlying \`IgnClient\` instance.
 */
export interface TypedRealtimeClient {
  /** Register a payload-typed handler for an event. */
  on<K extends RealtimeEventName>(
    name: K,
    handler: (payload: RealtimeEventPayloads[K]) => void,
  ): TypedRealtimeClient;
  /** Remove a previously registered handler. */
  off<K extends RealtimeEventName>(
    name: K,
    handler: (payload: RealtimeEventPayloads[K]) => void,
  ): TypedRealtimeClient;
  /** Register a handler that fires once for the event, then removes itself. */
  once<K extends RealtimeEventName>(
    name: K,
    handler: (payload: RealtimeEventPayloads[K]) => void,
  ): TypedRealtimeClient;
  /** Send a typed app event to the server (server must allow it). */
  send<K extends RealtimeEventName>(name: K, payload: RealtimeEventPayloads[K]): void;
  /** Open (or re-open) the WebSocket; idempotent while open/connecting. */
  connect(): TypedRealtimeClient;
  /** Close the socket and stop reconnecting (teardown on sign-out). */
  close(): void;
  /** Observe every event (name + payload) — debugging and smoke tooling. */
  onAny(cb: (name: RealtimeEventName, payload: unknown) => void): TypedRealtimeClient;
  /** Watch connection lifecycle changes. */
  onStatus(cb: (status: ClientStatus) => void): void;
  /** Remove a status watcher. */
  offStatus(cb: (status: ClientStatus) => void): void;
  /** Current connection status. */
  readonly currentStatus: ClientStatus;
  /** Register an error callback (decode failures, transport errors). */
  onError(cb: (err: Error) => void): void;
}

/**
 * Create a typed realtime client. \`on\`/\`send\` are checked against
 * \`RealtimeEventName\`; payload types flow from \`payloads.gen.ts\`.
 */
export const createRealtimeClient = (
  url: string,
  options?: Omit<IgnClientOptions<never>, "bindings">,
): TypedRealtimeClient => {
  const client = createClient(url, { ...options, bindings });
  return client as unknown as TypedRealtimeClient;
};
`;

/** Emit `realtime/rpc.gen.ts` — the typed RPC-over-WS client. */
const emitRpcGen = (): string => `// @generated by ignex sdk — DO NOT EDIT
import type { ClientStatus } from "@ignex/nova/client";
import type { TypedRealtimeClient } from "./client.gen";
import type { RpcMethodArgs } from "./payloads.gen";

/** Default round-trip budget for an RPC call. */
const DEFAULT_RPC_TIMEOUT_MS = 20_000;

/** Wire frame carried by the transport's \`rpc.response\` control event. */
interface RpcResponseFrame {
  id: string;
  ok: boolean;
  data?: string;
  error?: string;
}

/** A call awaiting its correlated response. */
interface PendingCall {
  resolve(value: unknown): void;
  reject(err: Error): void;
  timer: ReturnType<typeof setTimeout>;
}

/** Wire-level view of the realtime client used for the RPC channel. */
interface RpcTransport {
  on(name: string, handler: (frame: RpcResponseFrame) => void): unknown;
  off(name: string, handler: (frame: RpcResponseFrame) => void): unknown;
  onStatus(cb: (status: ClientStatus) => void): unknown;
  send(name: string, payload: unknown): void;
}

const transportOf = (client: TypedRealtimeClient): RpcTransport =>
  client as unknown as RpcTransport;

/** Error thrown for an RPC-level failure (carries the server's message). */
export class RpcError extends Error {
  /** Server status code (or a synthetic one: 408 timeout, 503 disconnected). */
  readonly status: number;
  constructor(message: string, status = 500) {
    super(message);
    this.name = "RpcError";
    this.status = status;
  }
}

/** Correlation id → pending call (module-scoped: one channel per client). */
const pending = new Map<string, PendingCall>();

let nextCorrelationId = 1;

/**
 * Parse a FAILED response frame's error envelope into an \`RpcError\`.
 * Current servers send JSON \`{ message, status }\`; legacy shapes
 * (\`{ error, status }\` or a plain string) are accepted too.
 */
export const parseRpcErrorResponse = (error: string | undefined): RpcError => {
  let message = "RPC failed";
  let status = 500;
  if (error !== undefined && error !== "") {
    try {
      const env = JSON.parse(error) as unknown;
      const record = typeof env === "object" && env !== null ? (env as Record<string, unknown>) : {};
      const text =
        typeof env === "string"
          ? env
          : typeof record.message === "string"
            ? record.message
            : typeof record.error === "string"
              ? record.error
              : null;
      if (text !== null) message = text;
      if (typeof record.status === "number") status = record.status;
    } catch {
      message = error;
    }
  }
  return new RpcError(message, status);
};

/** Wire one \`rpc.response\` frame to its pending call (unknown ids are dropped). */
export const dispatchRpcResponse = (frame: RpcResponseFrame): void => {
  const call = pending.get(frame.id);
  if (call === undefined) return;
  pending.delete(frame.id);
  clearTimeout(call.timer);
  if (frame.ok) {
    try {
      call.resolve(frame.data !== undefined && frame.data !== "" ? (JSON.parse(frame.data) as unknown) : null);
    } catch {
      call.reject(new RpcError("Malformed RPC response data"));
    }
  } else {
    call.reject(parseRpcErrorResponse(frame.error));
  }
};

/** Reject every in-flight call (socket dropped) so callers can retry. */
export const failAllPendingRpcCalls = (reason = "RPC socket disconnected"): void => {
  for (const call of pending.values()) {
    clearTimeout(call.timer);
    call.reject(new RpcError(reason, 503));
  }
  pending.clear();
};

/** Clients whose RPC dispatch (responses + disconnect handling) is wired up. */
const rpcBoundClients = new WeakSet<object>();

/** Bind response dispatch + disconnect fail-over to a client (once per client). */
const bindRpcChannel = (client: TypedRealtimeClient): void => {
  if (rpcBoundClients.has(client as unknown as object)) return;
  rpcBoundClients.add(client as unknown as object);
  const transport = transportOf(client);
  transport.on("rpc.response", dispatchRpcResponse);
  transport.onStatus((status) => {
    if (status === "disconnected" || status === "closed" || status === "reconnecting") {
      failAllPendingRpcCalls();
    }
  });
};

/**
 * Call an RPC method over the realtime channel. Sends an \`rpc.request\`
 * frame ({ id, method, payload: JSON-encoded args }) and resolves the
 * server's JSON result; rejects with \`RpcError\` on a business error,
 * timeout, or dropped socket.
 */
export const callRpc = async <M extends keyof RpcMethodArgs & string>(
  client: TypedRealtimeClient,
  method: M,
  args: RpcMethodArgs[M],
  opts?: { timeoutMs?: number },
): Promise<unknown> => {
  bindRpcChannel(client);
  const id = \`r\${Date.now().toString(36)}\${(nextCorrelationId++).toString(36)}\`;
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      pending.delete(id);
      reject(new RpcError(\`RPC timed out: \${method}\`, 408));
    }, opts?.timeoutMs ?? DEFAULT_RPC_TIMEOUT_MS);
    pending.set(id, { resolve, reject, timer });
    try {
      transportOf(client).send("rpc.request", { id, method, payload: JSON.stringify(args) });
    } catch (err) {
      clearTimeout(timer);
      pending.delete(id);
      reject(err instanceof Error ? err : new Error(String(err)));
    }
  });
};
`;

/** Emit `realtime/server.ts` — the typed server-side events facade. */
const emitServerFacade = (): string => `// @generated by ignex sdk — DO NOT EDIT
/**
 * Typed server-side events facade — use from routes, jobs and plugins:
 *
 *   import { emit, emitToUser, on } from "<sdk>/server";
 *   emit("order.created", { id: "o-1", at: 1 });
 *   on("order.created", (payload, ctx) => { ... });
 *
 * Backed by the module-global hub that \`novaPlugin\` binds at boot
 * (@ignex/nova/events). Handlers must be registered AFTER the hub binds
 * (e.g. from a plugin placed after realtimePlugin in app.config.ts).
 */
import {
  emit as _emit,
  emitToUser as _emitToUser,
  emitToClient as _emitToClient,
  emitToTopic as _emitToTopic,
  emitToGroup as _emitToGroup,
  on as _on,
  once as _once,
  off as _off,
} from "@ignex/nova/events";
import type { RealtimeEventPayloads } from "./payloads.gen";

/** Event names this app declares (derived from src/realtime.ts). */
export type RealtimeEventName = keyof RealtimeEventPayloads & string;

export const emit = <K extends RealtimeEventName>(
  name: K,
  payload: RealtimeEventPayloads[K],
): void => _emit(name as never, payload as never);

export const emitToUser = <K extends RealtimeEventName>(
  userId: string,
  name: K,
  payload: RealtimeEventPayloads[K],
): void => _emitToUser(userId, name as never, payload as never);

export const emitToClient = <K extends RealtimeEventName>(
  clientId: string,
  name: K,
  payload: RealtimeEventPayloads[K],
): void => _emitToClient(clientId, name as never, payload as never);

export const emitToTopic = <K extends RealtimeEventName>(
  topic: string,
  name: K,
  payload: RealtimeEventPayloads[K],
): void => _emitToTopic(topic, name as never, payload as never);

export const emitToGroup = <K extends RealtimeEventName>(
  group: string,
  name: K,
  payload: RealtimeEventPayloads[K],
): void => _emitToGroup(group, name as never, payload as never);

/** Handler receives the typed payload plus the nova event context. */
export const on = <K extends RealtimeEventName>(
  name: K,
  handler: (payload: RealtimeEventPayloads[K], ctx: unknown) => void,
): void => _on(name as never, handler as never);

export const once = <K extends RealtimeEventName>(
  name: K,
  handler: (payload: RealtimeEventPayloads[K], ctx: unknown) => void,
): void => _once(name as never, handler as never);

export const off = <K extends RealtimeEventName>(
  name: K,
  handler?: (payload: RealtimeEventPayloads[K], ctx: unknown) => void,
): void => _off(name as never, handler as never);

export type { RealtimeEventPayloads } from "./payloads.gen";
`;

/**
 * Emit `realtime/index.ts` — the package barrel.
 *
 * Deliberately does NOT re-export `./server` (the typed server-side events
 * facade): that module imports `@ignex/nova/events`, whose optional Redis
 * loader requires `node:module`'s `createRequire`, which breaks browser
 * bundles (`createRequire is not a function`). This barrel must stay
 * browser-safe so a frontend can `import { createRealtimeClient } from
 * "<pkg>"`. Server-side consumers import the facade from "<pkg>/server".
 */
const emitIndexTs = (): string => `// @generated by ignex sdk — DO NOT EDIT
export { controlEvents, events, schemas } from "./schema";
export { bindings, createRealtimeClient } from "./client.gen";
export type { TypedRealtimeClient } from "./client.gen";
export type { RealtimeEventPayloads, RpcMethodArgs } from "./payloads.gen";
export { callRpc, RpcError } from "./rpc.gen";
export * from "./wire";
`;

/** Emit the realtime package's `package.json`. */
const emitPackageJson = (ctx: SdkGenerateContext): string => {
  const { options } = ctx;
  const name = options.name ?? defaultPackageName(ctx);
  const version = options.version ?? "0.0.0";
  const description =
    options.description ??
    `Generated realtime SDK for the \`${ctx.serviceName}\` API (nova FlatBuffer wire stack + typed WebSocket client + typed RPC over WS).`;
  const pkg = {
    name,
    version,
    description,
    type: "module",
    sideEffects: false,
    // Sources ship directly — consumers bundle them (same model as a
    // hand-maintained realtime-bindings package).
    main: "./realtime/index.ts",
    module: "./realtime/index.ts",
    types: "./realtime/index.ts",
    exports: {
      ".": "./realtime/index.ts",
      "./schema": "./realtime/schema.ts",
      "./client": "./realtime/client.gen.ts",
      "./server": "./realtime/server.ts",
      "./rpc": "./realtime/rpc.gen.ts",
      "./payloads": "./realtime/payloads.gen.ts",
    },
    files: ["realtime", "README.md"],
    dependencies: {
      "@ignex/nova": "^0.1.1",
      "@sinclair/typebox": "^0.34.0",
    },
    license: options.license ?? "MIT",
    ...(options.repoUrl !== undefined ? { repository: { type: "git", url: options.repoUrl } } : {}),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
};

/** Default package name: `<scope>/<serviceName>-realtime-sdk`. */
const defaultPackageName = (ctx: SdkGenerateContext): string => {
  const base = `${ctx.serviceName}-realtime-sdk`;
  return ctx.options.scope !== undefined ? `${ctx.options.scope}/${base}` : base;
};

/** Emit the realtime package's README. */
const emitReadme = (ctx: SdkGenerateContext): string => {
  const { options, serviceName } = ctx;
  const name = options.name ?? defaultPackageName(ctx);
  const install = options.repoUrl !== undefined ? `npm install ${name}` : `npm install ${name}`;
  const local =
    options.localInstallPath !== undefined
      ? `\n## Local testing\n\n\`\`\`sh\nnpm install ${options.localInstallPath}\n\`\`\`\n`
      : "";
  return `# ${name}

Generated **realtime** SDK for the **${serviceName}** API — a nova FlatBuffer wire
stack, a typed WebSocket client, and typed RPC-over-WS calls, derived from the
app's \`src/realtime.ts\` declarations (\`realtime.json\`) and RPC manifest.

- \`@ignex/nova\` wire stack: generated decoders/encoders + \`makeBindings\` (see \`realtime/wire.ts\`).
- \`createRealtimeClient(url)\`: payload-typed \`on\`/\`once\`/\`send\` against the app's events.
- \`callRpc(client, method, args)\`: correlated request/response over the same socket.
- \`<pkg>/server\`: typed server-side \`emit\`/\`emitToUser\`/\`on\` facade (Bun only). It is NOT
  re-exported from the package root — the root stays browser-safe.

> Server-side (Bun) only:
> \`\`\`ts
> import { emit } from "${name}/server";
> \`\`\`

## Install

${install}${local}
## Quick start

\`\`\`ts
import { createRealtimeClient } from "${name}";
import { callRpc, RpcError } from "${name}/rpc";

const rt = createRealtimeClient("wss://api.example.com/ws", { reconnect: true }).connect();
rt.on("chat.message", (m) => console.log(m.body));
rt.send("chat.send", { orderId: "ord_1", body: "hello", clientTs: Date.now() });

try {
  const me = await callRpc(rt, "me.get", {});
} catch (err) {
  if (err instanceof RpcError && err.status === 401) console.error("auth required");
}
\`\`\`

## Regenerating

This package is generated by \`ignex sdk --platform realtime\`. Regenerate it whenever
the app's realtime declarations change; do not edit files under \`realtime/\` by hand.
`;
};

/** Deterministic file ordering for the emitted package. */
const byPath = (a: SdkFile, b: SdkFile): number => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0);

/**
 * Assemble the realtime package files: the generated nova stack plus the
 * framework-owned schema/payloads/client/rpc/barrel modules.
 */
const emitRealtimeFiles = async (ctx: SdkGenerateContext): Promise<readonly SdkFile[]> => {
  const input = requireRealtimeInput(ctx);

  const nova = await loadNovaGenerate();
  const generated = nova.generateBindings(
    {
      ...(input.schemas !== undefined ? { schemas: input.schemas } : {}),
      events: input.events,
      ...(input.controlEvents !== undefined ? { controlEvents: input.controlEvents } : {}),
    },
    { rust: false, ffiMode: "optional", subjectPrefix: input.subjectPrefix, force: true },
  );

  const files: SdkFile[] = [];
  for (const [rel, content] of Object.entries(generated.files)) {
    if (rel.startsWith("rust/") || rel === "README.md") continue;
    files.push({ path: packagePathOf(rel), content });
  }
  files.push(
    { path: "package.json", content: emitPackageJson(ctx) },
    { path: "README.md", content: emitReadme(ctx) },
    { path: "realtime/schema.ts", content: emitSchemaTs(input) },
    { path: "realtime/payloads.gen.ts", content: emitPayloadsGen(input) },
    { path: "realtime/client.gen.ts", content: emitClientGen() },
    { path: "realtime/server.ts", content: emitServerFacade() },
    { path: "realtime/rpc.gen.ts", content: emitRpcGen() },
    { path: "realtime/index.ts", content: emitIndexTs() },
  );
  return [...files].sort(byPath);
};

/**
 * The realtime SDK platform: emits an installable npm package carrying the
 * nova FlatBuffer wire stack, a typed WebSocket client and typed RPC calls,
 * derived from the app's realtime build artifacts.
 */
export const realtimePlatform: SdkPlatform = {
  id: "realtime",
  label: "Realtime",
  description:
    "npm package: nova FlatBuffer wire stack + typed WebSocket client + typed RPC-over-WS (from realtime.json / rpc-manifest.json).",
  generate(ctx: SdkGenerateContext): Promise<readonly SdkFile[]> {
    return emitRealtimeFiles(ctx);
  },
};
