/**
 * @fileoverview Public types for the Ignex SDK generation pipeline.
 *
 * An "SDK" is a standalone, framework-agnostic package derived from a compiled
 * app's artifacts (`manifest.json` + `openapi.json`). It lets frontend teams
 * install a typed client for the API — type-safe route calls, request
 * body/params/query types, and the OpenAPI document for their own tooling —
 * without pulling in any Bun-only framework code.
 *
 * The pipeline is multi-platform: each {@link SdkPlatform} emits its own
 * package from the same {@link SdkGenerateContext}. The TypeScript platform
 * (self-contained, zero-dependency ESM client + `.d.ts` types) is the
 * reference implementation; new platforms implement the same interface.
 */

/** Built-in SDK platform identifiers. */
export type SdkPlatformId = "typescript" | "openapi" | "flatbuffers" | "realtime";

/** A single generated file, relative to its package directory. */
export interface SdkFile {
  /** Path relative to the package directory (e.g. `dist/client.js`). */
  path: string;
  /** File content (UTF-8). */
  content: string;
}

/**
 * Per-route SDK input, derived from the compiled app's `manifest.json` route
 * entries merged with the matching OpenAPI operation's schemas.
 */
export interface SdkRouteInfo {
  /** HTTP method, uppercase (`GET`). */
  method: string;
  /** Route path (`/products/:id`). */
  path: string;
  /** Dynamic path parameter names, in template order. */
  paramNames: readonly string[];
  /** Whether the handler reads the request body (from the manifest). */
  usesBody: boolean;
  /** Whether the handler reads query parameters (from the manifest). */
  usesQuery: boolean;
  /** Request body JSON Schema (from OpenAPI `requestBody`), if any. */
  bodySchema?: unknown;
  /** Combined path-parameter object schema, if any. */
  paramsSchema?: unknown;
  /** Combined query-parameter object schema, if any. */
  querySchema?: unknown;
  /** Lowest 2xx response JSON Schema, if any. */
  responseSchema?: unknown;
  /** Response flavor from the manifest (`json` | `unknown` | …). */
  responseType: string;
}

/**
 * Realtime input, loaded from the build artifacts `<outDir>/realtime.json`
 * (written by `ignex build` from the app's `src/realtime.ts` declarations)
 * and `<outDir>/rpc-manifest.json` (written by the runtime RPC kit). All
 * schema values are TypeBox schemas in JSON form.
 */
export interface SdkRealtimeInput {
  /** NATS subject prefix baked into the generated nova bindings. */
  subjectPrefix: string;
  /** Named tables/enums referenced by events (`ChatMessage` → schema). */
  schemas?: Record<string, unknown>;
  /** App events: name → TypeBox payload schema. */
  events: Record<string, unknown>;
  /** Extra transport-internal control events (beyond the standard ones). */
  controlEvents?: Record<string, unknown>;
  /** RPC methods from `rpc-manifest.json`: name → TypeBox args schema. */
  rpcMethods?: Record<string, unknown>;
}

/**
 * Everything a {@link SdkPlatform} needs to emit its package: the resolved
 * routes, the canonical OpenAPI document, and the normalized SDK options.
 */
export interface SdkGenerateContext {
  /** Routes resolved from the compiled artifacts. */
  routes: readonly SdkRouteInfo[];
  /** The canonical OpenAPI 3.1 document (`openapi.json` artifact). */
  openapi: Record<string, unknown>;
  /** App/service name (from the manifest `serviceName`). */
  serviceName: string;
  /** Normalized SDK options (name, version, …) shared by all platforms. */
  options: SdkOptions;
  /**
   * Realtime declarations (`<outDir>/realtime.json` + `rpc-manifest.json`),
   * consumed by the realtime platform; absent when the app has none.
   */
  realtime?: SdkRealtimeInput;
}

/**
 * One SDK platform: emits a complete package (its own `package.json` +
 * sources) from the shared generation context.
 */
export interface SdkPlatform {
  /** Platform id (`typescript`, `openapi`, …). */
  id: string;
  /** Human-readable label for CLI output. */
  label: string;
  /** One-line description shown in `ignex sdk --help`. */
  description: string;
  /**
   * Emit the platform's package files (pure — no filesystem access). May be
   * async when a platform shells out to an optional codegen dependency
   * (e.g. the realtime platform's `@ignex/nova/generate`).
   */
  generate(ctx: SdkGenerateContext): readonly SdkFile[] | Promise<readonly SdkFile[]>;
}

/** A generated package for one platform. */
export interface SdkPackage {
  /** Platform id this package was generated by. */
  platform: string;
  /** Absolute package directory (written by {@link writeSdk}). */
  dir: string;
  /** The emitted files (relative to `dir`). */
  files: readonly SdkFile[];
}

/** Result of {@link generateSdk} / {@link writeSdk}. */
export interface SdkResult {
  /** Root directory holding the generated package(s). */
  rootDir: string;
  /** One generated package per selected platform. */
  packages: readonly SdkPackage[];
}

/** Options controlling SDK generation (normalized by {@link generateSdk}). */
export interface SdkOptions {
  /**
   * Absolute path to the compiled app's artifact directory — must contain
   * `manifest.json` and `openapi.json` (produced by `ignex build`).
   */
  outDir: string;
  /**
   * Directory the SDK package(s) are written to. Defaults to `<outDir>/sdk`.
   * With a single platform the package is written directly into this
   * directory; with several, each platform gets a subdirectory named after
   * its id.
   */
  packageDir?: string;
  /**
   * npm package name for the generated SDK (may include a scope, e.g.
   * `@acme/api-sdk`). Defaults to `<scope>/<serviceName>-sdk`.
   */
  name?: string;
  /** npm scope to prefix the default name with (e.g. `@acme`). */
  scope?: string;
  /** Package version (semver). Defaults to `0.0.0`. */
  version?: string;
  /** Platforms to generate. Defaults to `["typescript"]`. */
  platforms?: readonly SdkPlatformId[];
  /** Repository URL for README install instructions (e.g. GitHub HTTPS URL). */
  repoUrl?: string;
  /**
   * Absolute path to the generated package root. Emitted into the README as a
   * static local install target (`npm install <path>`) so frontend teams can
   * test the SDK on their device before it is tagged on GitHub / published.
   * With several platforms each package's README points at its own subdir.
   */
  localInstallPath?: string;
  /** SPDX license id for the generated `package.json`. Defaults to `MIT`. */
  license?: string;
  /** Short package description. Defaults to a generated summary. */
  description?: string;
}
