/**
 * @fileoverview TypeScript SDK platform.
 *
 * Emits a complete, self-contained npm package for frontend consumers:
 *
 * - `dist/client.js` — a zero-dependency ESM fetch client (no `@ignex/*`
 *   imports, works in browsers / Node / Bun), with per-route call shapes
 *   baked in at generation time.
 * - `dist/types.d.ts` — concrete request/params/query/response types derived
 *   from the OpenAPI schemas (via the JSON Schema → TS emitter).
 * - `dist/routes.d.ts` — the typed `IgnexRoutes` route map + `IgnexClient`
 *   contract (same DX as the compiler-generated client, self-contained).
 * - `openapi.json`, `package.json`, `README.md` — installable + documented.
 *
 * The platform is pure: {@link generateTypeScriptPlatform} returns
 * {@link SdkFile}s from the shared {@link SdkGenerateContext}.
 */

import { jsonSchemaToTs } from "./json-schema-to-ts";
import type { SdkFile, SdkGenerateContext, SdkPlatform, SdkRouteInfo } from "./types";

/** Path/name sanitizer: `/api/orders-ack` → `ApiOrdersAck`. */
export const pathToName = (path: string): string =>
  path
    .split("/")
    .filter(Boolean)
    .map((segment) => {
      const cleaned = segment.replace(/[^A-Za-z0-9]/g, "");
      return cleaned === "" ? "Route" : cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
    })
    .join("");

/** Whether the route's call shape carries path params. */
export const hasParams = (route: SdkRouteInfo): boolean =>
  route.paramNames.length > 0 || route.paramsSchema !== undefined;

/** Whether the route exposes query typing (schema or handler usage). */
export const hasQuery = (route: SdkRouteInfo): boolean =>
  route.usesQuery || route.querySchema !== undefined;

/**
 * Deterministic per-part type names shared by every emitted file.
 *
 * Names are reserved once, in a canonical order (routes sorted by path, parts
 * in a fixed order), so `types.d.ts` and `routes.d.ts` always reference the
 * same identifiers — even when two route paths sanitize to the same name.
 */
class TypeNameRegistry {
  private readonly names = new Map<string, string>();
  private readonly used = new Set<string>();

  /** Reserve (or return the already-reserved) name for a route part. */
  reserve(prefix: "Params" | "Query" | "Body" | "Response", route: SdkRouteInfo): string {
    const key = `${prefix}|${route.method}|${route.path}`;
    const existing = this.names.get(key);
    if (existing !== undefined) return existing;
    const base = `${prefix}_${route.method.charAt(0)}${route.method.slice(1).toLowerCase()}${pathToName(route.path)}`;
    let name = base;
    let n = 2;
    while (this.used.has(name)) {
      name = `${base}_${n}`;
      n += 1;
    }
    this.used.add(name);
    this.names.set(key, name);
    return name;
  }
}

/** Fallback params type when no params schema exists (mirrors the compiler). */
const paramsTypeFromNames = (names: readonly string[]): string => {
  if (names.length === 0) return "Record<string, never>";
  return `{\n${names.map((name) => `    ${name}: string;`).join("\n")}\n  }`;
};

/** `IgnexRoutes` entry for one route. */
const routeEntry = (route: SdkRouteInfo, names: TypeNameRegistry): string => {
  const method = route.method.toLowerCase();
  const lines: string[] = [`    ${method}: {`];

  if (hasParams(route)) {
    lines.push(`      params: ${names.reserve("Params", route)};`);
  }
  if (hasQuery(route)) {
    lines.push(`      query: ${names.reserve("Query", route)};`);
  }
  if (route.usesBody) {
    lines.push(`      body: ${names.reserve("Body", route)};`);
  }
  lines.push(`      response: ${names.reserve("Response", route)};`);
  lines.push("    };");

  return lines.join("\n");
};

/** Emit `dist/types.d.ts` — named, importable types per route part. */
export const emitTypesDts = (routes: readonly SdkRouteInfo[], ctx: SdkGenerateContext): string => {
  const resolveRef = (ref: string): unknown => {
    if (!ref.startsWith("#/")) return undefined;
    const parts = ref.slice(2).split("/");
    let node: unknown = ctx.openapi;
    for (const part of parts) {
      if (!isRecord(node)) return undefined;
      node = node[part];
    }
    return node;
  };

  const names = new TypeNameRegistry();
  const lines = [
    "// Auto-generated by Ignex SDK generator. Do not edit.",
    "",
    "// Concrete request/response types derived from the compiled OpenAPI document.",
    "",
  ];

  for (const route of routes) {
    if (route.paramsSchema !== undefined) {
      lines.push(
        `export type ${names.reserve("Params", route)} = ${jsonSchemaToTs(route.paramsSchema, { resolveRef })};`,
      );
    } else if (hasParams(route)) {
      lines.push(
        `export type ${names.reserve("Params", route)} = ${paramsTypeFromNames(route.paramNames)};`,
      );
    }

    if (route.querySchema !== undefined) {
      lines.push(
        `export type ${names.reserve("Query", route)} = ${jsonSchemaToTs(route.querySchema, { resolveRef })};`,
      );
    } else if (hasQuery(route)) {
      lines.push(
        `export type ${names.reserve("Query", route)} = Record<string, string | string[]>;`,
      );
    }

    if (route.bodySchema !== undefined) {
      lines.push(
        `export type ${names.reserve("Body", route)} = ${jsonSchemaToTs(route.bodySchema, { resolveRef })};`,
      );
    }

    lines.push(
      route.responseSchema !== undefined
        ? `export type ${names.reserve("Response", route)} = ${jsonSchemaToTs(route.responseSchema, { resolveRef })};`
        : `export type ${names.reserve("Response", route)} = unknown;`,
    );
    lines.push("");
  }

  return lines.join("\n");
};

/** Emit `dist/routes.d.ts` — the typed route map + client contract. */
export const emitRoutesDts = (
  routes: readonly SdkRouteInfo[],
  _ctx: SdkGenerateContext,
): string => {
  const names = new TypeNameRegistry();
  const imports = new Set<string>();

  for (const route of routes) {
    if (hasParams(route)) imports.add(names.reserve("Params", route));
    if (hasQuery(route)) imports.add(names.reserve("Query", route));
    if (route.usesBody) imports.add(names.reserve("Body", route));
    imports.add(names.reserve("Response", route));
  }

  const importLines = [...imports].map((name) => `  ${name},`).join("\n");

  const byPath = new Map<string, SdkRouteInfo[]>();
  for (const route of routes) {
    const group = byPath.get(route.path) ?? [];
    group.push(route);
    byPath.set(route.path, group);
  }

  const pathBlocks: string[] = [];
  for (const [path, group] of byPath) {
    const entries = group.map((route) => routeEntry(route, names)).join("\n");
    pathBlocks.push(`  ${JSON.stringify(path)}: {\n${entries}\n  };`);
  }

  return `// Auto-generated by Ignex SDK generator. Do not edit.
import type {
${importLines}
} from "./types";

// Per-route call signature, derived from the route's declared params/query/body:
//   params+query+body → (params, query, body, init?)
//   params+query      → (params, query, init?)
//   query+body        → (query, body, init?)
//   params+body       → (params, body, init?)
//   params            → (params, init?)
//   query             → (query, init?)
//   body              → (body, init?)
//   none              → (init?)
type IgnexRouteHandler<Route> =
  Route extends { params: infer P; query: infer Q; body: unknown }
    ? (params: P, query: Q, body: unknown, init?: RequestInit) => Promise<unknown>
    : Route extends { params: infer P; query: infer Q }
      ? (params: P, query: Q, init?: RequestInit) => Promise<unknown>
      : Route extends { query: infer Q; body: unknown }
        ? (query: Q, body: unknown, init?: RequestInit) => Promise<unknown>
        : Route extends { params: infer P; body: unknown }
          ? (params: P, body: unknown, init?: RequestInit) => Promise<unknown>
          : Route extends { params: infer P }
            ? (params: P, init?: RequestInit) => Promise<unknown>
            : Route extends { query: infer Q }
              ? (query: Q, init?: RequestInit) => Promise<unknown>
              : Route extends { body: unknown }
                ? (body: unknown, init?: RequestInit) => Promise<unknown>
                : (init?: RequestInit) => Promise<unknown>;

export type IgnexRoutes = {
${pathBlocks.join("\n")}
};

export type IgnexClient = {
  [Path in keyof IgnexRoutes]: {
    [Method in keyof IgnexRoutes[Path]]: IgnexRouteHandler<IgnexRoutes[Path][Method]>;
  };
};
`;
};

/** Emit `dist/client.d.ts` — the factory declaration + client options. */
const emitClientDts = (): string => `// Auto-generated by Ignex SDK generator. Do not edit.
import type { IgnexClient } from "./routes";

/** Options for {@link createApiClient}. */
export interface SdkClientOptions {
  /** Base URL of the API (e.g. \`https://api.example.com\`). */
  baseUrl: string;
  /** Headers applied to every request (merged under per-call headers). */
  headers?: Record<string, string>;
  /** Custom fetch implementation (defaults to the global fetch). */
  fetch?: typeof fetch;
  /** Attach credentials (\`"include"\` for cookies) to every request. */
  credentials?: RequestCredentials;
}

/** Error thrown by the generated client on non-2xx responses. */
export declare class ApiClientError extends Error {
  /** HTTP status code of the failed response. */
  status: number;
  /** Parsed response body (JSON or text), if any. */
  body: unknown;
  /** The raw \`Response\` object of the failed request. */
  response: Response;
}

/**
 * Create a fully typed API client for the generated routes.
 *
 * Calls are typed per route: \`api["/products/:id"].get({ id })\` or
 * \`api["/products"].post({ name, price })\` — body/params/query/response
 * types come from \`./routes\` and \`./types\`.
 */
export declare function createApiClient(options: SdkClientOptions): IgnexClient;
`;

/** Emit `dist/client.js` — the self-contained runtime client. */
type CallShape =
  | "none"
  | "params"
  | "body"
  | "params+body"
  | "query"
  | "params+query"
  | "query+body"
  | "params+query+body";

const emitClientJs = (routes: readonly SdkRouteInfo[]): string => {
  const routeEntries = routes
    .map(
      (r) =>
        `  ${JSON.stringify(`${r.method.toLowerCase()} ${r.path}`)}: ${JSON.stringify(r.path)},`,
    )
    .join("\n");

  const modeFor = (r: SdkRouteInfo): CallShape => {
    const params = hasParams(r);
    const query = hasQuery(r);
    const body = r.usesBody;
    const key = `${params ? "p" : ""}${query ? "q" : ""}${body ? "b" : ""}`;
    const map: Record<string, CallShape> = {
      p: "params",
      pq: "params+query",
      pb: "params+body",
      pqb: "params+query+body",
      q: "query",
      qb: "query+body",
      b: "body",
      "": "none",
    };
    return map[key] ?? "none";
  };

  // Keyed by the full "method path" (same key shape as ROUTES) — a bare path
  // collides when the same route template serves multiple methods with
  // different shapes (e.g. DELETE /gigs/:id = params vs PATCH = params+body).
  const argsEntries = routes
    .map(
      (r) =>
        `  ${JSON.stringify(`${r.method.toLowerCase()} ${r.path}`)}: ${JSON.stringify(modeFor(r))},`,
    )
    .join("\n");

  return `// Auto-generated by Ignex SDK generator. Do not edit.
// Self-contained typed client — no runtime dependencies.

export class ApiClientError extends Error {
  constructor(status, message, body, response) {
    super(message);
    this.name = "ApiClientError";
    this.status = status;
    this.body = body;
    this.response = response;
  }
}

const ROUTES = {
${routeEntries}
};

// Route template → call shape ("none" | "params" | "body" | "params+body" |
// "query" | "params+query" | "query+body" | "params+query+body").
const ROUTE_ARGS = {
${argsEntries}
};

const buildUrl = (path, params) => {
  let url = path;
  for (const [key, value] of Object.entries(params ?? {})) {
    url = url
      .replace(\`:\${key}\`, encodeURIComponent(String(value)))
      .replace(\`*\${key}\`, encodeURIComponent(String(value)));
  }
  return url;
};

// Serialize a query object to a "?a=1&b=x" suffix (array values repeat).
const buildQuery = (query) => {
  if (!query) return "";
  const parts = [];
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      for (const v of value) {
        parts.push(\`\${encodeURIComponent(key)}=\${encodeURIComponent(String(v))}\`);
      }
    } else {
      parts.push(\`\${encodeURIComponent(key)}=\${encodeURIComponent(String(value))}\`);
    }
  }
  return parts.length > 0 ? \`?\${parts.join("&")}\` : "";
};

// Deep-merge per-call init over the client-wide init so a per-call header
// doesn't clobber headers set on createApiClient (shallow spread would).
const mergeInit = (base, per) => {
  const out = { ...base, ...per };
  if (base?.headers && per?.headers) {
    out.headers = { ...base.headers, ...per.headers };
  }
  return out;
};

export const createApiClient = (options) => {
  const base = (options?.baseUrl ?? "").replace(/\\/+$/, "");
  const baseHeaders = options?.headers ?? {};
  const fetcher = options?.fetch ?? globalThis.fetch;
  const credentials = options?.credentials;
  const baseOptions = { headers: baseHeaders };

  const request = async (method, path, body, init) => {
    const isBody = body !== undefined;
    const headers = { ...baseHeaders, ...(init?.headers ?? {}) };
    if (isBody && typeof body !== "string") headers["content-type"] = "application/json";
    const response = await fetcher(base + path, {
      ...(credentials !== undefined ? { credentials } : {}),
      ...init,
      method,
      headers,
      ...(isBody ? { body: typeof body === "string" ? body : JSON.stringify(body) } : {}),
    });
    const text = await response.text();
    let parsed = null;
    if (text) {
      try {
        parsed = JSON.parse(text);
      } catch {
        parsed = text;
      }
    }
    if (!response.ok) {
      throw new ApiClientError(
        response.status,
        \`Request failed: \${response.status} \${response.statusText} \${path}\`,
        parsed,
        response,
      );
    }
    return parsed;
  };

  const routeHandler = (pathKey) => {
    const path = ROUTES[pathKey] ?? pathKey;
    const mode = ROUTE_ARGS[pathKey] ?? "none";
    const callUrl = (params, query) => buildUrl(path, params) + buildQuery(query);
    return new Proxy({}, {
      get(_, methodKey) {
        return async (...args) => {
          if (mode === "params+query+body") {
            const [params, query, body, init] = args;
            return request(methodKey.toUpperCase(), callUrl(params, query), body, mergeInit(baseOptions, init));
          }
          if (mode === "params+query") {
            const [params, query, init] = args;
            return request(methodKey.toUpperCase(), callUrl(params, query), undefined, mergeInit(baseOptions, init));
          }
          if (mode === "query+body") {
            const [query, body, init] = args;
            return request(methodKey.toUpperCase(), callUrl(undefined, query), body, mergeInit(baseOptions, init));
          }
          if (mode === "query") {
            const [query, init] = args;
            return request(methodKey.toUpperCase(), callUrl(undefined, query), undefined, mergeInit(baseOptions, init));
          }
          if (mode === "params+body") {
            const [params, body, init] = args;
            return request(methodKey.toUpperCase(), buildUrl(path, params), body, mergeInit(baseOptions, init));
          }
          if (mode === "params") {
            const [params, init] = args;
            return request(methodKey.toUpperCase(), buildUrl(path, params), undefined, mergeInit(baseOptions, init));
          }
          if (mode === "body") {
            const [body, init] = args;
            return request(methodKey.toUpperCase(), path, body, mergeInit(baseOptions, init));
          }
          const [init] = args;
          return request(methodKey.toUpperCase(), path, undefined, mergeInit(baseOptions, init));
        };
      },
    });
  };

  return new Proxy({}, {
    get(_, pathKey) {
      return routeHandler(pathKey);
    },
  });
};
`;
};

/** Emit `dist/index.d.ts` + `dist/index.js` — the package entry re-exports. */
const emitIndexFiles = (): SdkFile[] => [
  {
    path: "dist/index.d.ts",
    content: `// Auto-generated by Ignex SDK generator. Do not edit.
export { createApiClient, ApiClientError } from "./client";
export type { SdkClientOptions } from "./client";
export type { IgnexClient, IgnexRoutes } from "./routes";
`,
  },
  {
    path: "dist/index.js",
    content: `// Auto-generated by Ignex SDK generator. Do not edit.
export { createApiClient, ApiClientError } from "./client.js";
`,
  },
];

/** Emit the SDK `package.json`. */
const emitPackageJson = (ctx: SdkGenerateContext): string => {
  const { options } = ctx;
  const name = options.name ?? defaultPackageName(ctx);
  const version = options.version ?? "0.0.0";
  const description =
    options.description ??
    `Generated TypeScript SDK for the \`${ctx.serviceName}\` API (self-contained, zero-dependency typed client).`;
  const pkg = {
    name,
    version,
    description,
    type: "module",
    sideEffects: false,
    main: "./dist/index.js",
    module: "./dist/index.js",
    types: "./dist/index.d.ts",
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
      "./openapi.json": "./openapi.json",
    },
    files: ["dist", "openapi.json", "README.md"],
    license: options.license ?? "MIT",
    engines: { node: ">=18" },
    ...(options.repoUrl !== undefined ? { repository: { type: "git", url: options.repoUrl } } : {}),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
};

/** Default package name: `<scope>/<serviceName>-sdk`. */
const defaultPackageName = (ctx: SdkGenerateContext): string => {
  const base = `${ctx.serviceName}-sdk`;
  return ctx.options.scope !== undefined ? `${ctx.options.scope}/${base}` : base;
};

/** Emit the SDK `README.md`. */
const emitReadme = (ctx: SdkGenerateContext): string => {
  const { options, serviceName } = ctx;
  const name = options.name ?? defaultPackageName(ctx);
  const version = options.version ?? "0.0.0";
  const install =
    options.repoUrl !== undefined
      ? `npm install ${name}
# or install directly from the GitHub release tarball:
npm install ${options.repoUrl}/releases/download/sdk-v${version}/${name.replace("@", "").replace("/", "-")}-${version}.tgz`
      : `npm install ${name}`;

  const local =
    options.localInstallPath !== undefined
      ? `
## Local testing (before it is published)

The repo/release does not exist yet (or is not configured) — test this SDK on your
device straight from the generated package. From your frontend project:

\`\`\`sh
npm install ${options.localInstallPath}
# or install from the packed tarball (produced by \`ignex sdk\`):
npm install ${options.localInstallPath}/${name.replace("@", "").replace("/", "-")}-${version}.tgz
\`\`\`

As soon as the GitHub repo is available, run \`ignex sdk --push --release\` (or
\`--publish\` for npm) to distribute it, and the install command above switches
to the registry/release URL.
`
      : "";

  return `# ${name}

Generated TypeScript SDK for the **${serviceName}** API — install it in your frontend for
type-safe API calls and fast, schema-driven development.

- Self-contained: **zero runtime dependencies** (plain \`fetch\`), works in browsers, Node ≥ 18 and Bun.
- Typed routes: request bodies, path/query params and responses are derived from the compiled OpenAPI document.
- Ships \`openapi.json\` for your own tooling (codegen, mocks, docs).

## Install

${install}${local}

## Quick start

\`\`\`ts
import { createApiClient } from "${name}";

const api = createApiClient({
  baseUrl: "https://api.example.com",
  // headers: { Authorization: "Bearer …" },
  // credentials: "include", // cookies
});

// Path access mirrors the route map — fully typed per route:
const order = await api["/api/orders"].post({
  orderId: "ord_123",
  quantity: 2,
  totalCents: 4900,
});

const report = await api["/api/reports/:id"].get({ id: "42" });
const me = await api["/auth/me"].get();
\`\`\`

The call shape follows the route's declared inputs:

| Route shape | Call |
| --- | --- |
| \`params + body\` | \`api["/path/:id"].post(params, body, init?)\` |
| \`params\` only | \`api["/path/:id"].get(params, init?)\` |
| \`body\` only | \`api["/path"].post(body, init?)\` |
| neither | \`api["/path"].get(init?)\` |

## Errors

Non-2xx responses throw an \`ApiClientError\` with \`status\`, the parsed \`body\`, and the raw
\`response\`:

\`\`\`ts
import { ApiClientError } from "${name}";

try {
  await api["/auth/login"].post({ email, password });
} catch (err) {
  if (err instanceof ApiClientError && err.status === 401) {
    console.error(err.body); // server error payload
  }
}
\`\`\`

## Regenerating

This package is generated from the app's compiled artifacts
(\`manifest.json\` + \`openapi.json\`) by \`ignex sdk\`. Regenerate it whenever the API
changes, then tag/publish a new version:

\`\`\`sh
ignex sdk --version ${version} --push          # generate + git tag sdk-v${version}
ignex sdk --version ${version} --publish       # + publish to the npm registry
ignex sdk --version ${version} --release       # + attach the tarball to a GitHub release
\`\`\`
`;
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * The TypeScript SDK platform: emits a self-contained, installable npm
 * package with a typed zero-dependency client for the compiled routes.
 */
export const typescriptPlatform: SdkPlatform = {
  id: "typescript",
  label: "TypeScript",
  description:
    "Self-contained npm package: typed zero-dependency ESM client + .d.ts types + openapi.json.",
  generate(ctx: SdkGenerateContext): readonly SdkFile[] {
    const { routes } = ctx;
    const files: SdkFile[] = [
      {
        path: "package.json",
        content: emitPackageJson(ctx),
      },
      {
        path: "README.md",
        content: emitReadme(ctx),
      },
      {
        path: "openapi.json",
        content: `${JSON.stringify(ctx.openapi, null, 2)}\n`,
      },
      {
        path: "dist/types.d.ts",
        content: emitTypesDts(routes, ctx),
      },
      {
        path: "dist/routes.d.ts",
        content: emitRoutesDts(routes, ctx),
      },
      {
        path: "dist/client.d.ts",
        content: emitClientDts(),
      },
      {
        path: "dist/client.js",
        content: emitClientJs(routes),
      },
      ...emitIndexFiles(),
    ];
    return files;
  },
};
